### ISSUE TITLE
Maximum Call Stack Size Exceed When Piping into another stream

### ISSUE THREAD

**Issue by britztopher** [C2FO/fast-csv#103]
It appears that when using `fast-csv` with the listener 'data' the stream cannot be piped into another stream, otherwise, you get this error:

```
/Users/bistsls/projects/vlh/blah/node_modules/fast-csv/lib/parser/parser_stream.js:287
    emit: function (event) {
                   ^
RangeError: Maximum call stack size exceeded
```

Here is the code I am using:

``` javascript
var myCsvStream = fs.createReadStream('csv_files/myCSVFile.csv');
var csv = require('fast-csv');
var myData = [];

var myFuncs = { 
 parseCsvFile: function (filepath) {

  var csvStream;

  csvStream = csv
  .parse({headers: true, objectMode: true, trim: true})
  .on('data', function (data) {

       myData.push(data);

  })
  .on('end', function () {

    console.log('done parsing counties')
  });

  return csvStream;

 }
}

myCsvStream
.pipe(myFuncs.parseCsvFile())
.pipe(process.stdout);
```

The process.stdout is just so I can see that the data can continue on to the next stream, however, when adding pipe(process.stdout) or even a through2 duplex stream I get this maximum callstack reached error.

Issue is noted in SO post found here:
http://stackoverflow.com/questions/30620756/node-streams-get-maximum-call-stack-exceeded?noredirect=1

**Comment by ezodude** [comment]
+1 Having same issue as above.

**Comment by davicente** [comment]
+1

**Comment by doug-martin** [comment]
This should be fixed in the latest version.
