### ISSUE TITLE
Duplicate Column Names Omitted

### ISSUE THREAD

**Issue by spaggeti** [C2FO/fast-csv#105]
It appears that if you have duplicate column names in the CSV, they are omitted during conversion. There is no option to raise an error message in such events, nor is there an option to override this setting in the options and allow the sending of duplicate columns if you want to permit it.

**Comment by dustinsmith1024** [comment]
There might be another way to do this, but I think you have to set `headers=false` and manage the headers on your own by just grabbing the first row returned.

```js
var csv = require("fast-csv");

var CSV_STRING = 'a,b,a\n' +
                 'a1,b1,a11\n' +
                 'a2,b2,a22\n';

csv
 .fromString(CSV_STRING, {headers: false})
 .on("data", function(data){
     console.log(data);
 })
 .on("end", function(){
     console.log("done");
 });
```

```
➜  c2fo git:(TPF-31) ✗ node csv.js
[ 'a', 'b', 'a' ]
[ 'a1', 'b1', 'a11' ]
[ 'a2', 'b2', 'a22' ]
done
```

**Comment by vikeen** [comment]
:+1: 

This is an issue I ran into with dynamic headers at one point. Handling the first row myself just proved easier at the time.
