### ISSUE TITLE
Is it ever possible for the "end" callback to run before any of the "on" callbacks have run?

### ISSUE THREAD

**Issue by kevinburkeshyp** [C2FO/fast-csv#107]
Hi,
Is there any chance of a race between the time the handler for an `"on"` event is called, and the handler for an `"end"` event is called?

I'm just trying to read a bunch of rows into a dictionary, with something like this

``` javascript
var lines = []
csv.fromPath(argv['zone-file'], {
  headers: true
}).on('record', function(line) {
  lines.push(line);
}).on('end', function() {
  console.log(lines);
};
```

Is that _guaranteed_ to have every line by the time the `end` function runs?

**Comment by chriskinsman** [comment]
I am finding this not to be the case.  I find end is frequently called before the on("data", )

on("record", callback) I believe is deprecated in current versions

**Comment by doug-martin** [comment]
Doing some house cleaning.
