### ISSUE TITLE
Problem with escaped quotes

### ISSUE THREAD

**Issue by awsp** [C2FO/fast-csv#112]
I have got a csv file that is straightly exported from MySQL and I want to read and parse in Node.js. 
But I get errors whenever it reaches something that has escaped quotes on it. 
For example, 
"Foo \"Bar\"", "Baz", "", ""

This will give error 
```
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Parse Error: expected: '"' got: 'B'. at 'Bar" Foo",
at parseEscapedItem(node_modules/fast-csv/lib/parser/parser.js:79:19)
```

As a workaround, I ended up doing something like this, 
Reading it line by line and convert `\"` to `""` instead.
But it seems not possible to do it using other methods than fromString().

```
var csv = require("fast-csv");
var byline = require('byline');

var stream = byline(fs.createReadStream("mydata.csv", { encoding: 'utf8' }));
stream.on('data', function(line) {
  line = line.replace(/\\\"/g, '""');

  csv.fromString(line)
    .on("data", function (data) {
      // data 
    })
    .on("end", function () {

    });
});
```

Would that be potentially a bug?

**Comment by dustinsmith1024** [comment]
Did you try changing the escape character? You can pass it in on the options param.

`escape='\'`

**Comment by awsp** [comment]
Thanks for your reply.
The `escape='\'` will actually escape the quote and results in `Unexpected token ILLEGAL` error. 
Here is the code I used.
```js
var csv = require("fast-csv");

var line = '"Foo \"Bar\"", "Baz", "", ""';
  csv.fromString(line, { escape: "\"})
    .on("data", function (data) {
      console.log(data);
    })
    .on("end", function () {

    });
```
Error
```
csv.fromString(line, { escape: "\"})
                                 ^^^^^
SyntaxError: Unexpected token ILLEGAL
```


I have changed the escaping characters to the following, still having the same parse error I got from my last response. 

###### Case 1, escaping `\\\"`
```js
var csv = require("fast-csv");

var line = '"Foo \"Bar\"", "Baz", "", ""';
csv.fromString(line, { escape: "\\\""})
  .on("data", function (data) {
    console.log(data);
  })
  .on("end", function () {

  });

/** Error
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Parse Error: expected: '"' got: 'B'. at 'Bar"", "Ba
*/
```

###### Case 2, escaping only `\\`
```js
var csv = require("fast-csv");

var line = '"Foo \"Bar\"", "Baz", "", ""';
csv.fromString(line, { escape: "\\"})
  .on("data", function (data) {
    console.log(data);
  })
  .on("end", function () {

  });

/** Error
events.js:141
      throw er; // Unhandled 'error' event
            ^
Error: Parse Error: expected: '"' got: 'B'. at 'Bar"", "Ba
*/
```

**Comment by dustinsmith1024** [comment]
My fault I think you want `quote: '\\'` instead of escape.

```js
var csv = require("fast-csv");

var line = '"Foo \"Bar\"", "Baz", "", ""';
  csv.fromString(line, { quote:'\\'})
    .on("data", function (data) {
      console.log(data);
    })
    .on("end", function () {

    });
```

```
➜  c2fo git:(master) ✗ node test.js
[ '"Foo "Bar""', ' "Baz"', ' ""', ' ""' ]
```

**Comment by awsp** [comment]
That was the one! 
Didn't expect to pass `\\` to `quote`! 
I was passing `null` to `quote` earlier it didn't work. 

Thank you very much!

**Comment by Jeerjmin** [comment]
I have same problem

**Comment by doug-martin** [comment]
I dont think the solution above is doing what people think it is. It is setting the quote to a `\' character basically ignoring quoting in the examples.

@Jeerjmin can you provide a small example so I can try to reproduce and fix the underlying issue. Also what version of the package are you using?
