### ISSUE TITLE
Problem with not-escaped quotes

### ISSUE THREAD

**Issue by syymza** [C2FO/fast-csv#113]
Related to #112, I receive the following error whenever my CSV contains unescaped quotes:

``` javascript
Parse Error: expected: '"' got: 'B'. at 'Bree"","Mi
```

The line in my CVS is 

``` javascript
"hfhfgfg-erere-ddsd-sddsd-dasdasd","xxx@xxx.edu","XXX "Bree"","Mixx"
```

And my code is quite simple:

``` javascript
let fileStream = fs.createReadStream(config.csvPath);
let  csvStream = csv().on('data', (data) => console.log(data));
fileStream.pipe(csvStream);
```

I have tried different combination of `quote` and `escape`, without success

**Comment by fabiusss** [comment]
My error:
     Error: Parse Error: expected: '"' got: 'L'. at 'La Baia"",

resolved with:

    var csv = require("fast-csv");
    var stream = fs.createReadStream('myfile.csv');

    var csvConf={
      header:true,
      escape:'\"',
      quote:"'"
    }

    csv
     .fromStream(stream, csvConf)
     .on("data", function(data){

    })
     .on("end", function(){
    });

**Comment by doug-martin** [comment]
That error is letting you know that the csv has encountered an unescaped quote. WIthout the closing quote fast-csv cant reliably parse the file. 

Closing for now feel free to create a new issue if it needs to be discussed more.
