### ISSUE TITLE
How to filter out rows at csv.createWriteStream().transform()

### ISSUE THREAD

**Issue by tkang007** [C2FO/fast-csv#117]
Hi,
Filtering on csv().transform() can be imlemented by returning null instead of data. 
But, it does not work at csv.createWriteStream().transform().
I need to filter out some rows after parsing before format without adding intermediate transform.
Is there any simple way to filter out rows at transfrom function ?

**Comment by hijonathan** [comment]
Only a year late, but if anyone finds this, the place you'd want to send a PR for is probably here: https://github.com/C2FO/fast-csv/blob/master/lib/formatter/formatter_stream.js#L62

**Comment by 0x13a** [comment]
You can use this package instead `stream-csv-enhanced` https://github.com/uhop/stream-csv-enhanced/blob/master/tests/test_filter.js

**Comment by doug-martin** [comment]
This works in the latest version. 

Short example

```js
const stream = csv
    .format({ headers: true })
    .transform(row => (row.isValid ? row : null))
    .on('end', process.exit);

stream.pipe(process.stdout);

stream.write({ a: 'a1', b: 'b1', isValid: true });
stream.write({ a: 'a2', b: 'b2', isValid: false });
stream.write({ a: 'a3', b: 'b3', isValid: true });
stream.write({ a: 'a4', b: 'b4', isValid: false });
stream.end();
```

Output:
```
a,b,isValid
a1,b1,true
a3,b3,true
```
