### ISSUE TITLE
abnormal behavior on the parse

### ISSUE THREAD

**Issue by tkang007** [C2FO/fast-csv#118]
Hello,
I found the csv(), parser does not handle line-break properly.
When a writer feed string data which could be splited in the middle of a  line, the output of the parser could be partial data of full line.  When I feed line-boundary data, it work correct.  
Is there other simple workaround for this issue?

**Comment by ramiel** [comment]
I have the same problem. Depending on line-ending, a space is needed at the end of the line for the parser to work properly.
To be more precise with Unix LE a space is needed, with Windows LE the space has to be removed

**Comment by doug-martin** [comment]
Ill need a more concrete example in order to help.
