### ISSUE TITLE
`fromPath` breaks when delimiter is undefined

### ISSUE THREAD

**Issue by jcollum** [C2FO/fast-csv#119]
```
 at new ParserStream (node_modules/fast-csv/lib/parser/parser_stream.js:24:22)
      at Function.fromPath (node_modules/fast-csv/lib/parser/index.js:17:47)
```

All I had to do to get that to break was pass in an options object with a delimiter that was undefined. Sounds like there's a null check somewhere that's not handling undefined. 

Edit: 

change parser_stream.js:23 to: `delimiter = options.delimiter || ','` 

I can't imagine why `extended.has` would return true for an undefined value.

**Comment by doug-martin** [comment]
`extended.has` returns true because the delimiter property was explicitly set to undefined, and the options object actually has the property set.
