### ISSUE TITLE
CSV transformation in AWS lambda function results in write after end error

### ISSUE THREAD

**Issue by satyasrikantmantha** [C2FO/fast-csv#122]
I am trying to transform a CSV file using Fastcsv nodejs package. Interestingly, the code snippet works locally on my system well. However, if I try to integrate it with AWS lambda program it gives write after end error.

``` javascript
var stream = fs.createReadStream(s3EventInfo.inputDownloadLoc)
.pipe(csv.parse({headers: true}))
//pipe the parsed input into a csv formatter
.pipe(csv.format({headers: true}))
//Using the transfrom function from the formatting stream
.transform(function(row, next){
    transformLine(row, next);
})
.pipe(fs.createWriteStream(s3EventInfo.outputFileLoc))
.on("end", function(){
    callback();
});
```

Here is the error in aws logs..

``` txt
Error: write after end
at writeAfterEnd (_stream_writable.js:133:12)
at PassThrough.Writable.write (_stream_writable.js:181:5)
at write (_stream_readable.js:602:24)
at flow (_stream_readable.js:611:7)
at _stream_readable.js:579:7
at process._tickDomainCallback (node.js:486:13)
```

Please help in understanding and resolving the issue.

**Comment by Anxiom** [comment]
I see some solutions here  : http://stackoverflow.com/questions/33578998/stream-transformations-in-aws-lambda-result-in-write-after-end-error/33696017 
Could you please share the code in case it works.

**Comment by doug-martin** [comment]
This should be fixed in the latest version.
