### ISSUE TITLE
When enqueueing jobs from a stream, the last element is not enqueued

### ISSUE THREAD

**Issue by jkrenge** [C2FO/fast-csv#124]
I am using [fast-csv](https://github.com/C2FO/fast-csv) to iterate over a CSV file using a stream. For each row of the CSV file, I want to create a job in redis. Parsing a row is synchronous function. The whole thing looks like this:

``` javascript
var csvStream = fastCsv(_config.csvOptions)
  .on('data', function(data) {
    var stream = this;
    stream.pause();

    var payload = parseRow(data, _config);
    console.log(payload); // the payload is always printed to the console

    var job = kue.create('csv-row', {
        payload: payload
      })
      .save(function(err) {
        if (!err) console.log(new Date().toISOString() + ' > Enqueued at ' + job.id);
        else console.log(new Date().toISOString() + ' > Redis error ' + JSON.stringify(err));

        stream.resume();
      });
  })
  .on('end', function() {
    callback(); // this ends my parsing
  });
```

The simple `console.log(payload);` shows for every row of my CSV file, however the job is not created. To be precise, none of the outputs in the callback of `save` are being printed.

I assume, because it's the last row of the CSV file, the stream already emits `end` and so the last `kue.create()` cannot be executed before the process terminates?

Is there a way to halt the stream `end` until kue is done?

**Comment by jkrenge** [comment]
So I assume `end` is being called before my last element could be processed. I tried to switch away from flowing mode by using the `readable` event but noticed that this is not supported in fast-csv.

**Comment by Xeoncross** [comment]
I am trying to do something like this, but I try to process in batches of 1,000 to save db/queue/filesystem calls. Furthermore, if the `data` even callback encounters an error it needs to be able to stop the stream using `stream.destroy()` or some other method so it can safely shut down.

**Comment by doug-martin** [comment]
I would suggest creating a custom stream in this case and piping to it.
