### ISSUE TITLE
document v1.0.0 changes

### ISSUE THREAD

**Issue by palamccc** [C2FO/fast-csv#125]
0.5 -> 1.0 looks like major release, is there any major api change ? 
Also, 1.0 is available via npm, but released in github.

**Comment by dustinsmith1024** [comment]
There wasn't really any API changes. We just made it all work with the latest Node versions.  The record event is now officially gone. It's been deprecated for awhile so hopefully thats not an issue.

I put a small update in the History.md file.  https://github.com/C2FO/fast-csv/blob/master/History.md#v100

I forgot to tag a release, Ill go do that now.

**Comment by palamccc** [comment]
Got it, thanks. I missed History.md, i looked for CHANGELOG.md, then raised this issue.
