### ISSUE TITLE
Only processing 16 rows!

### ISSUE THREAD

**Issue by haroldSanchezb** [C2FO/fast-csv#128]
I have a file that has 50 rows when I try to read the document, only read the first 16, remove these 16 rows of the file and reads the next 16 ...

this is my configuration:

`fs.createReadStream(path.resolve("./files", "file.csv"))
    .pipe(csv.parse({headers: true}))
    .pipe(csv.format({headers: false, quote:" ", escape:" ", trim: true}))
    .transform(function(row) {`

What I have misconfigured?

**Comment by amos80m** [comment]
????? someone help

**Comment by dustinsmith1024** [comment]
Can you add some more info. Maybe put a gist up with your files or something and we can help out.
