### ISSUE TITLE
Library hangs if you stub the system time

### ISSUE THREAD

**Issue by kevinburkeshyp** [C2FO/fast-csv#129]
Occasionally in tests we stub the system time using `sinon.useFakeTimers`. This causes the fast-csv library to hang before writing any rows.

It looks like the problem is here: https://github.com/C2FO/fast-csv/blob/master/lib/extended.js#L16-L23. This library is not the only library with this problem: https://github.com/sinonjs/sinon/issues/960

I'm not completely sure why this is happening, or necessary, though it's certainly unexpected that stubbing the system time would cause CSV writing to fail. Debugging errors like this is particularly frustrating due to the lack of stack traces or useful information about running threads of execution while Javascript is executing.

**Comment by dustinsmith1024** [comment]
We use https://github.com/vesln/timekeeper for testing internally.  You might try using it instead of Sinon's built in time traveling.
