### ISSUE TITLE
Unable to export umlaut character

### ISSUE THREAD

**Issue by morwalz** [C2FO/fast-csv#133]
Hi, i am trying to export umlaut character. I tried to set encoding: "utf8" as well. But these char turns to strange ones. Any quick help ?

**Comment by dustinsmith1024** [comment]
Seems to be working for me when reading from a file or from inline text. Anything different for your situation? I am doing this on my mac.

test.csv
```
a,b,c
1,2,Ö
2,ö,ö
Ö,2,4
```

test.js
```js
var csv = require("fast-csv");

var CSV_STRING = 'a,b\n' +
                 'a1,b1\n' +
                 'a1,Ö\n' +
                 'Ö,b2\n';

csv
 .fromString(CSV_STRING, {headers: true})
 .on("data", function(data){
     console.log(data);
 })
 .on("end", function(){
     console.log("done");
 });

csv
 .fromPath("test.csv")
 .on("data", function(data){
     console.log(data);
 })
 .on("end", function(){
     console.log("done");
 });
```


```➜  c2fo-5 git:(BIL-5) ✗ node test
{ a: 'a1', b: 'b1' }
{ a: 'a1', b: 'Ö' }
{ a: 'Ö', b: 'b2' }
done
[ 'a', 'b', 'c' ]
[ '1', '2', 'Ö' ]
[ '2', 'ö', 'ö' ]
[ 'Ö', '2', '4' ]
done
```

**Comment by morwalz** [comment]
Hi. Thank you for your response. 

I am creating file using createWriteStream method.. this has a problem.

**Comment by dustinsmith1024** [comment]
Tried this locally and it worked fine as well.  Can you please provide and example?  Or better yet a failing test.

**Comment by dustinsmith1024** [comment]
Maybe this is the same as https://github.com/C2FO/fast-csv/pull/116. Im going to review and merge that now.

**Comment by dustinsmith1024** [comment]
pushed 1.1.0. Let me know if it doesn't fix your issues.

**Comment by morwalz** [comment]
Hi, I am writing a method like this and using content create a file. It still has a issue

var csvfilename = createfilename(filename);
var data = [];


    for (var i = exportdata.length - 1; i >= 0; i--) {
        data[i] = _.pick(exportdata[i], exportfilter);
    }
    ;


    var csvStream = fastcsv
            .createWriteStream({headers: true, quoteColumns: false, encoding: "utf8"})
            .transform(function (data, next) {
                setImmediate(function () {
                    next(null, data);
                });
                ;
            }),

        writableStream = fs.createWriteStream(csvfilename, {encoding: "utf8"});
    writableStream.on("finish", function () {

        fs.readFile(csvfilename, function read(err, data) {
            if (err) {
                return callback(null, exportdata);
            }

            var contentBase64 = new Buffer(data).toString('base64');
            var contentPlain = new Buffer(contentBase64, 'base64');
            var c = contentPlain.toString();

            var fileinfo =
            {
                contentBase64: contentBase64,
                content: contentBase64,
                filename: csvfilename
            };

            fs.unlinkSync(csvfilename);
            return callback(null, fileinfo);
        });
    });

    csvStream.pipe(writableStream);

    for (var i = 0; i < data.length; i++) {
        csvStream.write(data[i]);
    }
    csvStream.end();
