### ISSUE TITLE
Parse multiple CSV files - wrong data on '.on('data')...' event

### ISSUE THREAD

**Issue by Raphael-johanne** [C2FO/fast-csv#134]
Hi,

I use FAST CSV to parse multiple CSV files to import their content in mongodb.

The code below works with one file but does not with n files; I've got wrong data.

`
var events 		= require("events");
var util 		= require("util");
var CsvReader 	= require("./reader.js");
var fs 			= require("fs");
var csv 		= require("fast-csv");

function FamilyReader(config) {
	CsvReader.call(this, config);
}

util.inherits(FamilyReader, CsvReader);

FamilyReader.prototype.treat = function(processorCallBack, writerCallback) {

	var familyFiles = fs.readdir(this.config.path, function(err, files){
		files.forEach(function(file, index){
			
			var stream = fs.createReadStream(this.config.path +'/'+ file);
			 
			var csvStream = csv({headers: true})
			    .on("data", function(data){
			    	console.log(data + " " + file);
			    	processorCallBack.treat(data, false, writerCallback);
			    })
			    .on("end", function(){
			    	processorCallBack.treat(null, true, writerCallback);
			    });
			
			
			stream.pipe(csvStream);	
			
		}.bind(this));
	}.bind(this));
	
};

module.exports = FamilyReader;
`
'Console.log' return me this trace (with the files FOOTBALL_BALLOONS.csv and FOOTBALL_CLOTHING.csv).

[object Object]] FOOTBALL_BALLOONS.csv
**[object Object] FOOTBALL_CLOTHING.csv** <- ? 
[object Object] FOOTBALL_BALLOONS.csv
[object Object] FOOTBALL_BALLOONS.csv
[object Object] FOOTBALL_BALLOONS.csv
[object Object] FOOTBALL_BALLOONS.csv
[object Object] FOOTBALL_BALLOONS.csv
LAST
[object Object] FOOTBALL_CLOTHING.csv
[object Object] FOOTBALL_CLOTHING.csv
[object Object] FOOTBALL_CLOTHING.csv
[object Object] FOOTBALL_CLOTHING.csv
[object Object] FOOTBALL_CLOTHING.csv
[object Object] FOOTBALL_CLOTHING.csv
LAST

I would like to have all data of the first file and then all data of the second file. It seems the both are readed in the same time. The result expected is 

[object Object] FOOTBALL_BALLOONS.csv 
...
LAST
[object Object] FOOTBALL_CLOTHING.csv
...
LAST

Thanks in advance !

Raphael

**Comment by dustinsmith1024** [comment]
I think the output is just mixed, not the actual streams. Everything is asynchronous so the order of output is not guaranteed in your situation. 

Try storing the data in some object or array then printing them both out afterwards.  I think what you have is working correctly.

**Comment by Raphael-johanne** [comment]
Hi, 

Thank you for your answer. My problem is I can't store content in variable for memory problematic (imagine a file with 2 000 000 rows). I want to treat row one by one to avoid memory leak. My example is bad, I will give you a goud one.

Raphael

**Comment by dustinsmith1024** [comment]
I think you will just have to sequentially process all the streams then. So don't start the second stream until the first one has ended.
