### ISSUE TITLE
Keep going when parse error happens?

### ISSUE THREAD

**Issue by jbeuckm** [C2FO/fast-csv#135]
How can I ignore the bad line and keep processing the CSV? I have a huge CSV with a few quotes-within-quotes parsing errors. I can just ignore those lines or try to fix them.

This code prints the error but then just exits:
```

            .on('error', function(error) {
                console.log(error);
            })
```

**Comment by dustinsmith1024** [comment]
Yea, we actually just had a PR that addressed this. However, we don't think we can reliably know where to start parsing after an error.

You can check out that branch if you want to run a fork https://github.com/C2FO/fast-csv/pull/114.

This probably won't perform the best, but you could manually split the file based on newlines then pass them individually to fast csv. Then each row could fail and you would just ignore it.
