### ISSUE TITLE
Return wrong array formate like unicode return How can we set UTF-8.

### ISSUE THREAD

**Issue by higunjan** [C2FO/fast-csv#140]
Hi,
I want to read `CSV` or `xls` any one I just try right now to read CSV using these module But it's return me as Unicode format. Don't know why ? It's read as per row or Column ?

I used code like follow and read xls file. In CSV file it also return same output.

    `var fn = '/home/gunjan/sample.xls';
     var fs = require("fs");
     var csv = require("fast-csv")
     var stream = fs.createReadStream(fn);
 
     var csvStream = csv()
         .on("data", function(data){
              console.log(data);
         })
         .on("end", function(){
          console.log("done");
         });
 
      stream.pipe(csvStream);`

Output  : 

> ['\u0000\u0000\u0000�\u0000\u0000\u0000\u0013\u0000\u0000\u0000�\u0000\u0000\u0000\u0002\u0000\u0000\u0000�\u0004\u0000\u0000\u001e\u0000\u0000\u0000\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u001e\u0000\u0000\u0000\u0004\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u001e\u0000\u0000\u0000\u0010\u0000\u0000\u0000Microsoft Excel\u0000@\u0000\u0000\u0000\u0000�?q2��\u0001@\u0000\u0000\u0000�ԉ\u0003w��\u0001\u0003\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000��\u0000\u0000\u0006\u0002\u0002\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0002��՜.\u001b\u0010��\b\u0000+',
  '��0\u0000\u0000\u0000�\u0000\u0000\u0000\b\u0000\u0000\u0000\u0001\u0000\u0000\u0000H\u0000\u0000\u0000\u0017\u0000\u0000\u0000P\u0000\u0000\u0000\u000b\u0000\u0000\u0000X\u0000\u0000\u0000\u0010\u0000\u0000\u0000`\u0000\u0000\u0000\u0013\u0000\u0000\u0000h\u0000\u0000\u0000\u0016\u0000\u0000\u0000p\u0000\u0000\u0000']

What Happen  here please let me know.

**Comment by dustinsmith1024** [comment]
If the file is a true Excel xls file then you will need a library that can ready the proper Excel formats. Fast CSV will not work with Excel files only basic CSVs.
