### ISSUE TITLE
Appending to a csv

### ISSUE THREAD

**Issue by FallingSnow** [C2FO/fast-csv#143]
Is it possible to use fast-csv to append to a csv file?

**Comment by dleber** [comment]
Yes! Pass your flag in the fs.createWriteStream options argument, as follows:
    csv.writeToStream(fs.createWriteStream(fileName, {flags: 'a'}), data, options)

**Comment by 151ali** [comment]
the file content : 

id,data
p1,10
p2,20
p3,30
p4,40
p5,50


try this code :sweat_smile:
`
var fs = require('fs');
var csv = require('fast-csv');

csv
    .writeToStream(fs.createWriteStream("test.csv", 
        {flags: 'a'}),                  
[
       [""], //
       [ "p1","01"],
       ["p2","02"]
]
      , {headers:false} )`

**Comment by alilland** [comment]
@151ali your code almost works, however whenever you append the first row is not added to a new line😞

<img width="629" alt="Screen Shot 2019-07-03 at 4 50 41 PM" src="https://user-images.githubusercontent.com/14061357/60631134-bcdf4880-9db2-11e9-83b5-2e3acc3bad2f.png">

**Comment by doug-martin** [comment]
here is a simple example that should get close to what you need (its missing the error handling and other stuff but it is a starting point)

```js
const append = (file, rows = []) => {
    const csvFile = fs.createWriteStream(file, { flags: 'a' });
    csvFile.write('\n');
    csv.writeToStream(csvFile, rows, { headers: false })
}

csv.writeToStream(fs.createWriteStream('test.csv'),
    [
        { a: 'a1', b: 'b1', c: 'c1' },
        { a: 'a2', b: 'b2', c: 'c2' },
        { a: 'a3', b: 'b3', c: 'c3' },
    ],
    { headers: true })
    .on('finish', () => {
        append('test.csv', [
            { a: 'a4', b: 'b4', c: 'c4' },
            { a: 'a5', b: 'b5', c: 'c5' },
            { a: 'a6', b: 'b6', c: 'c6' },
        ]);
    });
```

```csv
a,b,c
a1,b1,c1
a2,b2,c2
a3,b3,c3
a4,b4,c4
a5,b5,c5
a6,b6,c6
```

**Comment by loretoparisi** [comment]
@doug-martin I'm not sure I understand, I normally do like

```javascript
csvStream = FastCSV.createWriteStream({
        // first row is cols header
        headers: true
        // delimiter
        , delimiter: '\t'
        // character to use to escape values that contain a delimiter. If you set to null then all quoting will be ignored
        //, quote: '"'
        // The character to use when escaping a value that is quoted and contains a quote character
        , escape: '"'
        // ignore empty rows
        , ignoreEmpty: true
        // discard columns that do not map to a header.
        , discardUnmappedColumns: false
        // consider empty lines with too few fields as error
        , strictColumnHandling: false
    });
    var writableStream = fs.createWriteStream(out_file)
    csvStream.pipe(writableStream);
    writableStream.on("finish", function () {
        logger.info("closed csv file: %s", out_file)
    });
```

Now how to write to the file in the append mode with this approach? Adding `{ flag: 'a' }` to both ` fs.createWriteStream` and `FastCSV.createWriteStream` does not seem to help.

**Comment by doug-martin** [comment]
@loretoparisi what version of node and `fast-csv` are you using?

 In the example above there are two different writes

* The first time I write I create a write stream using the native node `fs` module and do not provide the flag.
* The second time in the `append` method I do provide the flag to the native node `fs` module and set headers to false so they are not written again.

The `fast-csv` method does not accept the flags option. Another thing to note is that the example above is using the `3.x` version of `fast-csv`

**Comment by loretoparisi** [comment]
@doug-martin I'm always using the latest version available on npm, so I assume the api is still working...

**Comment by doug-martin** [comment]
@loretoparisi the reason I was asking about the version is because `createWriteStream` is not in the latest version of `fast-csv` is has been replaced with `csv.format`.

I would be hesitant to add the append method to `fast-csv` because of the edge cases invloved (column order, previous encoding, all the options etc) that I think are better handled by the developer. 

This could be added to the documentation or maybe a FAQ page explaining the basics of how to do this.

**Comment by kuzdogan** [comment]
You can try this as a workaround not to write headers again
```
const csvStream = csv.format({
  headers: fs.existsSync(FILE_NAME) ? false : true,
  includeEndRowDelimiter: true
});
```
