### ISSUE TITLE
fast-csv inserts columns when parsing CSVs with only spaces for field values

### ISSUE THREAD

**Issue by icedawn** [C2FO/fast-csv#144]
When parsing CSV file with only spaces for field values, fast-csv gets the number of columns wrong (should be 12 in my example, but it gets 14).  

Here's a trace ...

> /Users/crump/wrk/fast-csv/test/issues.test.js:156
>                     throw err;
>                     ^
> 
> Error: Unexpected Error: column header mismatch expected: 12 columns got: 14
>     at ParserStream.self.__transform (/Users/crump/wrk/fast-csv/lib/parser/parser_stream.js:136:48)
>     at ParserStream.__parseLineData [as __handleLine] (/Users/crump/wrk/fast-csv/lib/parser/parser_stream.js:64:18)
>     at /Users/crump/wrk/fast-csv/lib/parser/parser_stream.js:89:22
>     at asyncIterator (/Users/crump/wrk/fast-csv/lib/extended.js:12:17)
>     at Function.asyncEach (/Users/crump/wrk/fast-csv/lib/extended.js:30:10)
>     at ParserStream.extended.extend.__processRows (/Users/crump/wrk/fast-csv/lib/parser/parser_stream.js:87:18)
>     at /Users/crump/wrk/fast-csv/lib/parser/parser_stream.js:177:34
>     at headerHandler (/Users/crump/wrk/fast-csv/lib/parser/parser_stream.js:155:13)
>     at ParserStream.__parseLineData [as __handleLine] (/Users/crump/wrk/fast-csv/lib/parser/parser_stream.js:81:20)
>     at ParserStream.extended.extend.__processHeaders (/Users/crump/wrk/fast-csv/lib/parser/parser_stream.js:159:18)
>

**Comment by jaypozo** [comment]
I may have a related issue - with dashes `-` adding an additional column when they are the field value.

**Comment by jaypozo** [comment]
I just installed v2.0.0 and this error does not exist.
