### ISSUE TITLE
Some rows incorrectly parsed for large csv files

### ISSUE THREAD

**Issue by joeldouglass** [C2FO/fast-csv#146]
Some rows are being skipped with the data value being output as an empty array for large files (>40,000 rows).

This is easy to replicate. Pass the attached csv file into the following script -

```
const fs = require('fs'),
  csv = require('fast-csv');

var filePath = process.argv[2];

var row = 0;

fs.createReadStream(filePath)
  .pipe(csv.parse({ headers: false }))
  .on('data', function(d){
    row += 1;
    if(!d[0]){
      console.log(`Failure in Row: ${row}`, d);
    }
  });
```

[large.zip](https://github.com/C2FO/fast-csv/files/372447/large.zip)

**Comment by dustinsmith1024** [comment]
Weird, is it always happening on line 44775 for you?

For me it seems like no data is actually being lost, it's just adding another data event an empty object.   I tweaked the lines a bit and as you can see below it's printing out the 3 rows, but also adding a different blank one.

```
111111
0.123456789
222222
```

```
row 44773 [ '111111' ]
row 44774 [ '0.123456789' ]
row 44775 []
Failure in Row: 44775 [] [ '0.123456789' ]
row 44776 [ '222222' ]
```

@aheuermann or @doug-martin might have some ideas too.

**Comment by joeldouglass** [comment]
It's always 44775 for this csv. The really strange thing though is that the row # that errors is different if you slightly alter the header row. Change it from `test` to `t` and the row failure changes to 19194. Then change it to `testtest` and the error goes away completely. It doesn't seem to matter if you have the `headers` flag set to true or false.
