### ISSUE TITLE
Use multiple data tables on same csv.

### ISSUE THREAD

**Issue by rishab-yumist** [C2FO/fast-csv#147]
Hello,

I'm trying to create something like the following (mentioned in the image).

![screen shot 2016-07-26 at 2 34 20 pm](https://cloud.githubusercontent.com/assets/13828707/17132147/17910a24-533e-11e6-9f0f-65c25460db57.png)

Using this code, 

```
var fs = require('fs');
var csvStream = csv
.createWriteStream({headers: true})
var fileName = moment().valueOf() + ".csv";
writableStream = fs.createWriteStream(path + fileName);

csvStream.pipe(writableStream);

csvStream.write({"Abc": "DEF"});

csvStream.write({"S.No.": "","Item": "Date", "Quantity": moment().format("DD-MMM-YYYY"), "#Unit": "","Unit": "","Pre-packaging": "","Dispatch": ""});

```

The output file has only one column Abc. How can I use write to have multiple varying columns?

@dustinsmith1024 Could you help me on this?

**Comment by dustinsmith1024** [comment]
So you want a top section and then a different section below it for the data?

The easiest would probably be to just make to files then combine them later on.  So write the header out to a file, write the data out to a file, then combine the two with generic Node 'fs' commands.

**Comment by rishab-yumist** [comment]
Yes. 

Is there no option to use multiple sections within the same file @dustinsmith1024?

**Comment by rishab-yumist** [comment]
Also, is there an option to directly convert the csv file generated to pdf too using node?

**Comment by dustinsmith1024** [comment]
No options for multiple sections.  You could try and get clever with how you make your data object and potentially get it to work.  I think that'd be more work and you would have to stuff the headers into the data.

So something like this might work.  I am not sure how it would handle the empty columns in the top sections. You might have to put blank columns in there to match the columns in the bottom section.

```
var topSection = [
  ['date', '2015-02-34'],
  ['time', '5:00pm'],
  ['DC', 'whatever'],
  ['', ''],
 ];

var bottomSection = [
  [ 'SO', 'Item', 'Quantity', 'Lead'],
  [ '1', 'Item1', '2', 'Lead1'],
  [ '2', 'Item1', '2', 'Lead2'],
];

var allData = topSection.concat(bottomSection);

...the write out the data like normal
```

There is no PDF writing in fast csv. If all you need is a PDF and not a CSV, I would suggest just using something like https://github.com/marcbachmann/node-html-pdf and write HTML tables, then make a PDF.  No need for fast csv at all.
