### ISSUE TITLE
Print Separator/Table Border

### ISSUE THREAD

**Issue by rishab-yumist** [C2FO/fast-csv#148]
Hello,

I want to print my csv in the form of a table. 

Since CSV doesn't support any form of formatting like table borders etc, can the seperator be changed to | and printed?

Expecting output in this format.
![screen shot 2016-07-27 at 8 01 47 pm](https://cloud.githubusercontent.com/assets/13828707/17178941/fb926abe-5434-11e6-9703-47bb65582d3d.png)

**Comment by dustinsmith1024** [comment]
Yea, you can use the `delimiter=','` option to change it to anything that is 1 letter.

**Comment by dustinsmith1024** [comment]
But your not going to get the borders look like you want.  If you really want that I don't think fast csv is the solution.
