### ISSUE TITLE
Trim not working correctly

### ISSUE THREAD

**Issue by zatziky** [C2FO/fast-csv#151]
Version I am using is **2.1.0**

For the code

```
const csv = require('fast-csv');

csv.fromPath('network-templates.csv', {ltrim: true, rtrim:true}) // also tried with {trim:true}
            .on('data', line => console.log(line))
            .on('end', () => console.log('done'));
```

and data (notice the white space)

`a , basdf   , c`

I get this result:

> [ 'a ', ' ', 'basdf   ', ' ', 'c' ]
> done

**Comment by k0emt** [comment]
I see the same issue with fromStream

**Comment by doug-martin** [comment]
This should be fixed in the latest version.
