### ISSUE TITLE
JSON as field value fails

### ISSUE THREAD

**Issue by yanickrochon** [C2FO/fast-csv#152]
I'm exporting some data from an SQL database and, while LibreOffice Calc can import the data just fine, fast-csv fails.

For example, one line is exported as CSV like this

"123";"Item Name";"{"bgColor":"#888888","fgColor":"#000000"}"

and the parser fails as it thinks that the field is `"{"` and expects the next char to be a semi-colon. The parser should continue until another delimiter is matched, then see if all escape chars are even. If the escape chars are odd, then the delimiter is supposed to be part of the field value and the parser keeps on going.

Test cases should ensure that

```
"hello";"world"     => [ "hello", "world" ]
"hel;lo";"world"    => [ "hel;lo", "world" ]     (delimiter within odd escapes)
"hel";"lo";"world"  => [ "hel", "lo" ]
"hel"lo";"world"    => [ "hel\"lo", "world" ]    (next char is not a delimiter)
"hel""lo";"world"   => [ "hel\"\"lo", "world" ]  (...)
```

The condition should be

```
if next char is escape then increment escape count and buffer
else if next char is delimiter then
  if escape count is odd then increment buffer
  else set next field value and reset buffer
else increment buffer
```

**Comment by doug-martin** [comment]
All of the examples given are valid and parse just fine except `"hel"lo";"world"` because of the unescaped quote, this line could be interpreted a number of different ways and I think an error in this case is better than potentially parsing the csv incorrectly.

**Comment by doug-martin** [comment]
Ill look into an option to relax some of the restrictions.
