### ISSUE TITLE
simple example fail

### ISSUE THREAD

**Issue by etfstest** [C2FO/fast-csv#153]
Here's what I'm doing:

``` js
// expects data to be array of arrays or array of objects
function writeCsv( fileName, data ) {
  var stream;
  var numRecs = ( data[0] instanceof Array ) ? data.length - 1 : data.length;  // array assumed to have header as first record
  stream = fs.createWriteStream(fileName + ".csv");
  csv.writeToStream( stream, data, {headers: true}); 
  console.log("wrote " + numRecs + " records to " + fileName + ".csv"); 
 // stream.end();  
}
```

That works fine, except the file is written only after everything ends. If I uncomment stream.end(), the file is created but nothing is written to it. I'm mystified about what's happening. 

You might add a really simple use case like the above to your documentation. Your documentation seems to be aimed at highly experienced persons. For me, this example is baffling:

``` js
csv
   .writeToStream(fs.createWriteStream("my.csv"), [
       {a: "a1", b: "b1"},
       {a: "a2", b: "b2"}
   ], {headers: true})
   .pipe(ws);
```

What's ws? Earlier in your examples it's a write stream. Why are you piping to ws after you've already called writeToStream?

If you would just throw a few bones to the clueless, your work probably would be valuable to a much greater number of persons.

**Comment by doug-martin** [comment]
This should be fixed in the latest version. 

I have updated the docs to try to help with the issue you described where undeclared variables are no longer referenced.
