### ISSUE TITLE
Having issue with calling callback funtion into it function

### ISSUE THREAD

**Issue by mitgo1990** [C2FO/fast-csv#160]
Hi,

I am unable to set data:
JS file one readcsv.js:
`   var CSVData = function(param ,callback) {
        var fs = require('fs');
        //var fastCsv = require("fast-csv");
        var csv = require("fast-csv");

```
    var stream = fs.createReadStream('TestData.csv');

    param = param || 'TC002';

    csv
        .fromStream(stream, {
            headers: true
        })
         .transform(function(data, next){
             MyModel.findById(data.id, next);
         })         
        .validate(function(data) {
            return data.TCID === param; //TCID from csv
        })
        .on("data-invalid", function(data) {
            //do something with invalid row 
        })
        .on("data", function(data) {
            console.log(data);
            callback(data);
        })
        .on("end", function() {
            console.log("done");
        });

};

module.exports = CSVData;`
```

JS file two enterData.js
`
var DataExtractor = require("../helper/readcsv.js");
describe("dataPage", function() {
    it('Verify user is able to get data and enter', function() {
        DataExtractor('TC001', function(data) {
            console.log('TCID', data.TCID);
            console.log('I1', data.I1);
            console.log('I2', data.I2);
            //I am not sure why but steps after this like are not work when I have DataExtractor inside of "it" function.
            browser.wait(function() {
                return browser.driver.isElementPresent(by.id('SessionDateTB'));
            }, 20000);

```
        expect(browser.getCurrentUrl()).toContain('http://someURL.com/');
        return browser.getCurrentUrl().then(function(url) {
            browser.get(url + '?session= 2016 - 08 - 2 ');
            browser.wait(function() {
                return browser.driver.isElementPresent(by.id('someElement'));
            }, 20000);
            dataPage.changeDate.get(1).click();
            browser.driver.sleep(2000);
            dataPage.changeDate.get(2).click();
            browser.driver.sleep(3000);
            browser.pause();
        });
    });
});
```

});
`
What I am trying to do is I have csv file with TCID number from TC001 to TC010 with headers "I1" to "I10" . I am trying to get TC002 values (this is working fine. I am able to get TC002). Issue I am having is I am unable to set data. 

Currently soon as "console.log('inside Verify user is able to change Test Date', data.I2);" runs Script stops without any error. 

Can someone please help me with this?

Thank you,

**Comment by doug-martin** [comment]
Doing some house cleaning. Reopen if this is still an issue.
