### ISSUE TITLE
If 'data-invalid' event happens, that row shouldn't be sent to transform function

### ISSUE THREAD

**Issue by rightaway** [C2FO/fast-csv#162]
If the `data-invalid` event happens, the `transform` function is then called with null data. An invalid row shouldn't be sent to transform to begin with, since it's invalid. Or if it is, it should be the array of delimited values, like what `data` is in the `data-invalid` callback.

```
  .on('data-invalid', (data) => {
    console.log('invalid row', data)  // Array of delimited values
  })
  .transform((data) => {
    console.log(data)  // null
  })
```

**Comment by doug-martin** [comment]
This should be fixed in the latest version
