### ISSUE TITLE
'data-invalid' event happening twice per row when validate function exists

### ISSUE THREAD

**Issue by rightaway** [C2FO/fast-csv#163]
```
  .validate(data => data)
  .on('data-invalid', data => {
    console.log('invalid', data)
  })
```

Here, the console.log happens twice per row but it should just happen once. The first time is an array of the delimited values. The second time is `null`.

If the validate function is removed, then the console.log only happens the first time with the array of values.

**Comment by doug-martin** [comment]
With out a better example with an example csv and the full parsing code I cant properly reproduce.
