### ISSUE TITLE
inserts spurious field on last line of parse

### ISSUE THREAD

**Issue by etfstest** [C2FO/fast-csv#165]
Test file test.csv (first two lines delimited with linefeed):
f1,f2,f3
1,text, a1
1,text, a1

 var readDocs = fs.createReadStream( './test.csv' );
 var parseDocs = csv.parse({objectMode: false});
 readDocs.pipe(parseDocs).pipe(process.stdout);

Produces (running node version 4.6.0):

["f1","f2","f3"]["1","text"," a1"]["1","text"," "," a1"]

Eliminate the space before a on the third line and you get:

["f1","f2","f3"]["1","text"," a1"]["1","text","a1"]

Or, alternatively, add a linefeed to the third line of the test file and it also parses correctly:

["f1","f2","f3"]["1","text"," a1"]["1","text"," a1"]

Thoughts?

**Comment by patrickdevivo** [comment]
Yes! I'm seeing the same issue on parsing many of my CSVs and it's driving me crazy

**Comment by dustinsmith1024** [comment]
We don't have anyone actively looking into this.  If either of you could write some tests or try to make a fix we will gladly merge it in.

**Comment by idris** [comment]
I'm seeing the same issue.  It's only with files without newlines at the end.  I hacked around it by just appending a newline to the file before processing it with fast-csv.

**Comment by idris** [comment]
@dustinsmith1024 I just pushed up a PR with a failing test case: https://github.com/C2FO/fast-csv/pull/174

Hope this helps get the issue resolved.
