### ISSUE TITLE
{ headers: ["column1", "column2", ... ] } issue

### ISSUE THREAD

**Issue by HoosierMike** [C2FO/fast-csv#168]
When you use this syntax there is no way to set { headers: true } thus you get the first "data" block which is the headers and you have to add a cheesy flag to your code to ignore the first call to data() {}

**Comment by DiglidiDudeNG** [comment]
Getting the same problem.

**Comment by dustinsmith1024** [comment]
Makes sense.  Feel free to submit a PR and we will merge it in.

**Comment by josemigallas** [comment]
@anyone already working on this? I'd like to give it a try

**Comment by DiglidiDudeNG** [comment]
Go right ahead, champ.

**Comment by josemigallas** [comment]
So PR sent, any chance of getting a review? :grin:

**Comment by jefffriesen** [comment]
It would be great to get this merged.

**Comment by dustinsmith1024** [comment]
It's merged, just the docs are waiting right?

**Comment by jefffriesen** [comment]
Yep, you're right.

**Comment by asabhaney** [comment]
I've submitted a PR for the docs, it's ready to be merged in: https://github.com/C2FO/fast-csv/pull/182

**Comment by jamesearl** [comment]
Still seeing the old behavior in fast-csv@^2.4.1.
