### ISSUE TITLE
How to prefix 'sep=delimiter' in a write stream

### ISSUE THREAD

**Issue by chacestew** [C2FO/fast-csv#171]
Hi,

We are using .createWriteStream to write an object to csv using the keys as headers. I need to add 'sep=,' to the start of the csv while keeping headers intact - how is the best way to go about this?

**Comment by dustinsmith1024** [comment]
Can you just write that afterwards?  Once you're done writing the CSV just open a new file and write 'sep=' then concat the new CSV.

Thats just an idea, I don't know how you could accomplish it with fast-csv directly.  Assuming I understand what your trying to do correctly.

**Comment by doug-martin** [comment]
You can write that before hand if you create your stream.

```js
const ws = fs.createWriteStream("my_file.csv");
ws.write('sep=,')

// now write to the stream
csv.format().pipe(ws) 
// or
csv.writeToStream(ws, [ /* rows */ ])
```
