### ISSUE TITLE
encoding limitation 

### ISSUE THREAD

**Issue by Kamill90** [C2FO/fast-csv#172]
In string_decoder.js I see there are 3 encoding options:
switch (this.encoding) {
    case 'utf16le':...
    case 'utf8':...
    case 'base64':...

I need to load csv with polish symbols (ex. "łódź"), but using all 3 options i get: 
[ '齤਍' ],
[ '��d�' ],
[ 's/Nknw0K' ]

not even close. I guess it's supposed to be encoded with Windows1250. 

How can I handle it?

**Comment by florianbepunkt** [comment]
@Kamill90 Have you ever found a solution to this? Facing a similiar problem. Thank you.

**Comment by Kamill90** [comment]
Yes. But it turned that problem in some other place. Finally I use utf8 but in place where I create request to API I need to : Buffer.from(variable_with_polish_letter_from_parsed_file, 'utf8').toString('latin1'). I dont know if it's helpful for you. If you describe your problem maybe I can help.

**Comment by florianbepunkt** [comment]
thank you!
