### ISSUE TITLE
final format issue

### ISSUE THREAD

**Issue by Kamill90** [C2FO/fast-csv#173]
Hi, I need to load csv with two colums. As output I get rows of objects, like 
`{key1 : value1, key2 : value2}
{key1 : value1, key2 : value2}
{key1 : value1, key2 : value2}
{key1 : value1, key2 : value2}
{key1 : value1, key2 : value2}`

pretty close, but I need to get array of objects

`[{key1 : value1, key2 : value2},
{key1 : value1, key2 : value2},
{key1 : value1, key2 : value2}] ...`

How may I reach it?

**Comment by doug-martin** [comment]
Can you not collect your rows.

```js
const CSV_STRING = [
    'a,b',
    'a1,b1',
    'a2,b2',
].join(EOL);

const rows = [];
csv
    .fromString(CSV_STRING, { headers: true })
    .on('error', error => console.error(error))
    .on('data', row => rows.push(row))
    .on('end', rowCount => console.log(`Parsed ${rowCount} rows`, rows));

```

Output:

```
Parsed 2 rows [ { a: 'a1', b: 'b1' }, { a: 'a2', b: 'b2' } ]
```
