### ISSUE TITLE
Last line of CVS with a space after each delimiter not processed correctly 

### ISSUE THREAD

**Issue by KimCoCat** [C2FO/fast-csv#177]
There appears to be a problem with mapping data from the last line of a CSV file that contains a space after the delimiter. If the last line has a carriage return at the end of the line the data is mapped correctly.

**Sample csv:**
A1, A2, A3, A4
B1, B2, B3, B4
C1, C2, C3, C4

**Sample code to process the above:**
exports.test = csvData => {
    const dataArray = [];
    const options = { discardUnmappedColumns: true, trim: true, headers: ['Col1', 'Col2', 'Col3', 'Col4'] };
    csv
        .fromString(csvData, options)
        .on('data', (data) => {
        dataArray.push(data);
        })
        .on('end', () => {
        console.log(dataArray)
        });
};

**Output**
[ { Col1: 'A1', Col2: 'A2', Col3: 'A3', Col4: 'A4' },
  { Col1: 'B1', Col2: 'B2', Col3: 'B3', Col4: 'B4' },
  { Col1: 'C1', Col2: ' ', Col3: 'C2', Col4: ' ' } ]

First 2 lines processed correctly, Col 2 of the last line takes the space after the delimiter as its value, the data for column 2 is then mapped to Col 3

if removing option - 'discardUnmappedColumns: true' an error it thrown :
Unexpected Error: column header mismatch expected: 4 columns got: 7

**Comment by btok** [comment]
+1

**Comment by lsps9150414** [comment]
+1

**Comment by Ijmir** [comment]
+1

**Comment by dbshoupe** [comment]
I am seeing this issue as well.

**Comment by dustinsmith1024** [comment]
Just a heads up, no one is actively looking into this. If you want to submit a PR we can push it through and release it.

**Comment by doug-martin** [comment]
This is fixed in the latest version
