### ISSUE TITLE
arabic language issue

### ISSUE THREAD

**Issue by akelmj** [C2FO/fast-csv#178]
hi,

when i run this code:
`        csv.writeToPath(DestFile, [{ key: "واحد", value: "مثال" }], { headers: true, encoding: "utf8" })
            .on("finish", function () {
                console.log("done!", DestFile);
            });`

i get this result:

![image](https://cloud.githubusercontent.com/assets/8736967/24000475/006fa2be-0a64-11e7-9ec3-8bdc22f01fee.png)

the correct result must be like this:
![image](https://cloud.githubusercontent.com/assets/8736967/24000596/51f18cf6-0a64-11e7-9762-4593ca897b0a.png)

how to fix this issue?

ragards.

**Comment by nabaragpaul** [comment]
you can try . transform function with some localize js to convert the language to english . may be ...

**Comment by doug-martin** [comment]
If you can provide a sample output csv that you expect I can try to fix.

**Comment by hbsoftco** [comment]
I have same problem!
