### ISSUE TITLE
Setting the BOM on write

### ISSUE THREAD

**Issue by bizarrochris** [C2FO/fast-csv#180]
Hi, we use the npm module to create csv exports and are generally very happy, however we still have the issue with utf-8 encoding, that excel does not recognise the files as utf-8 immediately.

According to: http://stackoverflow.com/questions/155097/microsoft-excel-mangles-diacritics-in-csv-files
adding the BOM would be the quickest fix.
Is there a way to add this to the stream. Our code looks like this (we use express.js):

```JAVASCRIPT

const csvOptions = {
            headers: true,
            delimiter: ';',
            transform: function(entry) {
//do stuff
            }
          };
          response.set('Content-Type', 'text/csv; charset=utf-8');
          response.set('Content-Disposition', 'attachment; filename="export.csv"');
          csv.write(transactions, csvOptions).pipe(response);

```

If there is no way to do it, an option would be amazing to set the BOM.
Thx in advance.

**Comment by dustinsmith1024** [comment]
I am not quite sure how to do this. Maybe you can do it like https://github.com/wdavidw/node-csv/issues/84#issuecomment-21707484?

You might have to make an extra stream and pipe one through the other though.  Maybe someone else can provide a better example.

**Comment by dustinsmith1024** [comment]
Or see: https://github.com/keystonejs/keystone/issues/748#issuecomment-226993349

**Comment by bizarrochris** [comment]
Thank you for the options - will check them out asap. 
However, having a BOM in the options would still make a lot of sense inmho.

**Comment by harryluo91** [comment]
Hi @bizarrochris did you find a way to work around this? We are also having the same issue but couldn't get it working with a stream.

**Comment by doug-martin** [comment]
Added in `v3.4.0` there is a new option called `writeBOM` that you can set to `true` to have the `BOM` character written.
