### ISSUE TITLE
multiple rows

### ISSUE THREAD

**Issue by adrianp12** [C2FO/fast-csv#181]
I am making an asynchronous request that essentially takes a parameter from a row from an "in.csv", then returns an array that I want to write each item to it's own row in "out.csv".

For example, I might read a row, get a http response with 5 values in an array. I want to write those 5 values to 5 rows in the "out.csv".

Is it possible to write several rows at once?

Something like this:

[
    ["a", "b", "c"],
    ["a1", "b1", "c1"],
   ["a2", "b2", "c2"]
]

**Comment by brenwell** [comment]
Hello everyone, I have the same question. Is this possible somehow?

**Comment by nateGeorge** [comment]
Yes you can do it like

```nodejs
var fs = require('fs');
var csv = require('fast-csv');

csv
   .writeToStream(fs.createWriteStream("my.csv"), [
       ["a", "b"],
       ["a1", "b1"],
       ["a2", "b2"]
   ], {headers: true});
```
