### ISSUE TITLE
escape fails

### ISSUE THREAD

**Issue by RolandasRazma** [C2FO/fast-csv#187]
There is several bug reports with this but all of them very abstract without easy reproducible sample...

```javascript
const csv = require('fast-csv');

csv.fromPath("bug.txt", { headers: false, quote: "|", delimiter: ",",  escape: '\\' })
    .on("data", async (data) => {
        console.log('data');
    });
```

will fall with "expected: '|' got: 'b'. at 'b|"

CSV (bug.txt):
`|a|,|\|,|b|`

**Comment by gtuk** [comment]
Could be related to #196 . I guess reserved characters don't get escaped correctly

**Comment by doug-martin** [comment]
In this example there is an uneven number of quotes (`|`) the first part `|a|` gets parsed fine the issue is with `|\|,|b|` the second pipe is escaped and it finds a 3rd with more data.
