### ISSUE TITLE
Streaming much slower than parsing CSVs in memory

### ISSUE THREAD

**Issue by eschwartz** [C2FO/fast-csv#189]
I'm trying to figure out what's going on here, and thought you might have some ideas...

Here's what I was doing:
- Create a read stream of a CSV file from S3
- Pass it through the fast-csv parser (transform) stream
- Pass it though my own transform stream, to do some work on the data
- Transform the data back to CSV, with fast-csv
- Write it to a write stream on S3

I'm working with a file that is ~60k lines / 8Mb. I ran the code on a Lambda function with 128M of memory, and it took 120 seconds. I did some performance tests on the code locally, and found that the performance impact of my own data transformation logic is negligible.

So I tried a different approach, and read the entire file into memory, parsed it with PapaParse, and wrote it back to S3. This time, it took <10s on a 120M lambda function.

I originally chose this library, because I thought streaming the data all the way through would be more performant than downloading the file to memory. But this seems not to be the case. Is there something about streams I don't understand? Or are there some performance optimizations that you can make if you're working on the entire file in memory, that you can't with a stream of data?

**Comment by dustinsmith1024** [comment]
I haven't done much with csv's lately, but I agree, the 120 seconds seems too slow.

In general I don't think streaming is supposed to be faster.  It should help with hitting memory limits though.  So if you only have 128mb of memory then I think the streaming approach is correct.  If you can be sure your CSV's are small, then it might not matter.

You're account for lamba function 'warm up' time in these timings right?

@doug-martin might have some more insight.

**Comment by TechnotronicOz** [comment]
I use FastCSV to write three CSV files to S3, then grab those file streams, merge them so we can create a "merged" file and stream that back to S3. The file sizes can vary but are usually 3-5mb and the entire operation takes < 10-15 seconds.

@eschwartz do you have a test case that you could share? We might be able to help identify what may be going on.

**Comment by doug-martin** [comment]
WIll need more info to help debug. Reopen if this is still an issue.
