### ISSUE TITLE
Is there a way to modify only one header with the renameHeader option

### ISSUE THREAD

**Issue by psbyron3** [C2FO/fast-csv#191]
Hey all,

First off, this lib has been working pretty great for me thus far nice job! That said, there's one thing I'm having trouble with. I need to change just one header, specifically the first header and that's it. I also have different csvs of unknown header lengths, so I'm not able to explicitly declare the headers.

I just tried to modify only the first header as such:
`const csvStreamOptions = { 
    delimiter: ',', 
    renameHeaders: true, 
    headers: ['storeId'], 
    objectMode: true, 
    trim: true 
};`

Here's an error snippet:
`Error: Unexpected Error: column header mismatch expected: 1 columns got: 5
    at ParserStream.self.__transform (/Users/pseidel/Desktop/Projects/labs-node-api/node_modules/fast-csv/lib/parser/parser_stream.js:134:48)
    at ParserStream.__parseLineData [as __handleLine] (/Users/pseidel/Desktop/Projects/labs-node-api/node_modules/fast-csv/lib/parser/parser_stream.js:6`

This particular csv has 5 headers, but again that will change. I reviewed all the open and closed issues and didn't see anything related to this issue. It's worth noting I'm using an outdated version.

Currently using v.0.5.7

So my q is: Is this functionality already done and I just need to update my version? Or is this still an open issue? Thanks in advance!

**Comment by doug-martin** [comment]
This is something that you should probably try to solve with the `transform` functionality.

Doing some house cleaning so Im going to closing for now. Reopen if this is still an issue for you.
