### ISSUE TITLE
headers case sensitivity

### ISSUE THREAD

**Issue by janpansa** [C2FO/fast-csv#195]
I think your documentation should include that headers are handled **case insensitive** when specifying them as an **array**, however, if not specified as an array, they are handled strictly case sensitive.

This had me confused for a few hours.

Also, when specifying headers as an array, if they are not in the correct order or have columns missing, no error is given and no data is processed. An error only appears when too many headers is present, not too little. I think this should be mentioned in the docs as the only thing mentioned is "You may alternatively pass an array of header names which must match the order of each column in the CSV, otherwise the data columns will not match." , however I think it should read " otherwise the data columns will not match and NO DATA WILL BE IMPORTED".

Let me know if you agree, thx !

**Comment by aspiringguru** [comment]
this seems a useful addition to documentation. thanks for pointing it out.

**Comment by doug-martin** [comment]
I added some docs around the headers with the `strictColumnHandling` option which addresses one part of your issue.

Im not sure I understand the case sensitivity issue, I know its been a while but if you could provide a short example demonstrating the issue I may be able to help.
