### ISSUE TITLE
Problem with Pipe character as delimiter

### ISSUE THREAD

**Issue by gtuk** [C2FO/fast-csv#196]
There seems to be a problem when you using the Pipe ("|") character as a delimiter the parsing doesn't seem to work because the pipe is a special character (or matching) in a regex and it doesn't get escaped.

parser.js -> line 16
`SEARCH_REGEXP = new RegExp("(?:\\n|\\r|" + delimiter + ")"),
`
Can someone confirm this problem or know how to fix it without adding the code?

**Comment by doug-martin** [comment]
Duplicate of #187 will address under that issue.

**Comment by doug-martin** [comment]
This was has been fixed in the `3.x` versions of the package. See https://github.com/C2FO/fast-csv/blob/master/src/parser/ParserOptions.ts#L67
