### ISSUE TITLE
Cannot parse non-quoted entries containing escaped quotes

### ISSUE THREAD

**Issue by alubbe** [C2FO/fast-csv#197]
I am trying to parse row that contain non-quoted entries with escaped quotes inside of them, like this one:
```
some entry,""Surrounded by escaped quotes"" entry continued,next entry
```
Unfortunately, I get this error:
```
Error: Parse Error: expected: '"' got: 'S'. at 'Surrounded
```
I realize it would be great to just add single quotes around the entire entry, but unfortunately I cannot control how the CSV is created, I only consume it. Is there a setting that I can change to parse this? `csv-parse` has a `relax` setting that allows this kind of input.

You can reproduce this by running this in the cli:
```
node -e "console.log(string=\`some entry,\"\"Surrounded by escaped quotes\"\" entry continued,next entry\`);require('fast-csv').fromString(string, {}).on('data', console.log)" # attempts to parse the entry as I receive it, crashes
node -e "console.log(string=\`some entry,\"\"\"Surrounded by escaped quotes\"\" entry continued\",next entry\`);require('fast-csv').fromString(string, {}).on('data', console.log)" # modifying the entry allows parsing, but I cannot fix the input csv reliably
```

**Comment by doug-martin** [comment]
Im not sure If this is something we should fix it with something like the suggestion in #152 
Either way I think it should be an opt in feature.

**Comment by doug-martin** [comment]
Closing in favor of #152
