### ISSUE TITLE
Can I put `undefined` to columns without values?

### ISSUE THREAD

**Issue by basharov** [C2FO/fast-csv#200]
Is it possible to make those fields that are empty `undefined` instead of an empty string?

Here is an example:

    firstname,lastname
    john,doe
    jack,

Here as a result for `jack` I'd like to see this:

    {
        firstname: 'jack'
        lastname: undefined
    }

**Comment by dustinsmith1024** [comment]
I don't think so.  Can you just use the `data` event to transform the value?

Or just `#map` everything afterwards.

**Comment by doug-martin** [comment]
@dustinsmith1024 is correct if you need empty strings to be changed to `undefined`. `fast-csv` only works with strings and does not try to make assumptions about how you want your fields formatted/transformed.
