### ISSUE TITLE
If the last value is missing I am getting a data-invalid event even with proper delimiters.

### ISSUE THREAD

**Issue by rayjennings3rd** [C2FO/fast-csv#201]
I have strictColumnHandling=true & headers=true.  If a line ends with something like:

a,b,c,d,e,,,

instead of

a,b,c,d,e,,,last

This is causing the data-invalid but the last column is just empty for that particular row.

**Comment by jkrenge** [comment]
Try the option `strictColumnHandling: false`, it helps me with those cases sometimes.

**Comment by evgenius** [comment]
+1, I'm facing this issue as well.
And I can't use `strictColumnHandling: false` as I need to make sure my CSV file is valid.

**Comment by Slayess** [comment]
I'm facing the same issue.
No answer since 18 months, this project has been abandoned ? :(

**Comment by doug-martin** [comment]
I'll take a look at this sometime in the next day or two. Have you tried the latest release `v3.0.1`?

**Comment by doug-martin** [comment]
This is fixed in the lastest version.

```js
const CSV_CONTENT = [
    'h1,h2,h3,h4,h5,h6,h7,h8',
    'a,b,c,d,e,,,',
    'a,b,c,d,e,,,last',
].join('\n');

csv
    .parseString(CSV_CONTENT, { headers: true, strictColumnHandling: true })
    .on('data', data => console.log('DATA: ', JSON.stringify(data)))
    .on('error', err => console.log('ERROR: ', err))
    .on('end', rowCount => console.log('END: ', rowCount));
```

Output:
```
DATA:  {"h1":"a","h2":"b","h3":"c","h4":"d","h5":"e","h6":"","h7":"","h8":""}
DATA:  {"h1":"a","h2":"b","h3":"c","h4":"d","h5":"e","h6":"","h7":"","h8":"last"}
END:  2
```

**Comment by rayjennings3rd** [comment]
My request in keeping in sync with MS SQL studio was for a pipe character | (not a colon character)

The colon is used in too many things, Day to Day that escaping is needed. Pipe character for regular text (name, address, etc) is just about guaranteed not to be present.

Raymond Jennings III
