### ISSUE TITLE
Handle line breaks in rows in csv

### ISSUE THREAD

**Issue by NeerajSonu** [C2FO/fast-csv#205]
[input.txt](https://github.com/C2FO/fast-csv/files/1505836/input.txt)
I am trying to read a CSV which has delimiter '|' and in this CSV, it has line breaks in a single row. The CSV sample is attached here.
Code through which I am doing it as:
`var stream = fs.createReadStream('input.csv');
                    stream.pipe(csv.parse({headers: true, delimiter: '|',
                        rowDelimiter:'\r\n'}))
                        .transform(function (row) {
                            console.log(row)
                            return row;
                        });`

So, when I am consoling the rows, I am getting 4 rows instead of 2. Any help would be appreciated.

**Comment by FunkyShu** [comment]
Your CSV is malformed.  According to https://tools.ietf.org/html/rfc4180 Section 2.6:

> Fields containing line breaks (CRLF), double quotes, and commas
>        should be enclosed in double-quotes.  For example:
> 
>        "aaa","b CRLF
>        bb","ccc" CRLF
>        zzz,yyy,xxx

Row 2 Column 13 should be double quoted.

**Comment by pthieu** [comment]
@NeerajSonu how'd you solve this?
