### ISSUE TITLE
`headers: false` and `objectMode=true` do not work

### ISSUE THREAD

**Issue by wzup** [C2FO/fast-csv#209]
These two options do not work
```
headers: false,
objectMode: true
```
Headers are always returned no matter `headers: false`. And data is always an array no matter `objectMode=true`

**Comment by ogsalman** [comment]
@wzup I think there has to be a header for every column. If you have a column without a header, you have the option to pass in an array of your own to enact as the header.

**Comment by doug-martin** [comment]
Ill need a more complete example to help you with this issue. Is this on the formatting or parsing side? 

Closing for now, reopen if you can provide a working example that demonstrates the issue.
