### ISSUE TITLE
How to know it reached the end of the file when error occurred on the last row

### ISSUE THREAD

**Issue by ravenjam** [C2FO/fast-csv#210]
If there's an error at the end of the file, the 'end' event doesn't trigger, only 'error' event triggers. How can I know it reached the end of the file?

**Comment by dustinsmith1024** [comment]
Haven't tried this in awhile, but I thought `error` stopped processing the file altogether. So `end` would not be triggered.  Could be wrong, but it should be easily testable.

**Comment by ravenjam** [comment]
@dustinsmith1024 Thank you for the quick reply!  The on 'error' does not stop processing the file which is actually what I want. My intention is to push all rows that can't be parsed into an array and respond back. It's just that I can't tell if it has reached the end.

**Comment by dustinsmith1024** [comment]
Okay so just confirming, so if the last row is an `error` then it does not emit an `end` event?

I am not sure if there is a good workaround there.  You could set up some kind of event listener/timer on your own and if you don't get any messages then assume its done.

Feel free to look at the code and send a PR in with a test.  We can review it and publish it.  None of us are actively updating the code though.

**Comment by ravenjam** [comment]
@dustinsmith1024 Thank you for the reply. If I get time I will try to PR
