### ISSUE TITLE
Parser ignores null values in last column

### ISSUE THREAD

**Issue by jheising** [C2FO/fast-csv#211]
I have the following CSV file:

```
"date","analysis_group","humidity","temperature"
"2018-01-08 00:00:00.000","Group 2",,"91.34"
"2018-01-08 00:00:00.000","Group 1","41.17",
... more lines following
```

The first row (after the header) properly returns 4 columns with an empty value for the 3rd column.
The second row only returns 3 columns— it ignores the last value.

Funny enough if I remove the quotes around the second row it seems to work as expected:

```
"date","analysis_group","humidity","temperature"
"2018-01-08 00:00:00.000","Group 2",,"91.34"
"2018-01-08 00:00:00.000","Group 1",41.17,
... more lines following
```

Both rows report 4 columns in this instance.

Note: I am instantiating the csv parser with no (i.e. default) options.

**Comment by doug-martin** [comment]
This is fixed in the latest version. 

Feel free to reopen if you still experience the issue but there are tests around this exact problem now.
