### ISSUE TITLE
proposal: expose headers on parser stream

### ISSUE THREAD

**Issue by shaunc** [C2FO/fast-csv#212]
I have csv I would like to parse. My task is to duplicate blocks of rows based on identifiers in the first few columns. I would like to add a few columns at the beginning, and leave the rest of the columns unchanged.

Currently, I cannot use the headers to access the first few columns, because I don't know the order of the rest of the columns. It isn't too much of a pain to use without headers; however, it would be convenient if I could access the headers in order so that I could re-emit rows with the succeeding columns in order.

**Comment by doug-martin** [comment]
If you can provide a working example of what you currently have to do, I could probably help. I suspect you could probably do this with the `transform` functionality but without more context Im not sure. 

Closing for now but you can reopen this issue if you can provide an example.
