### ISSUE TITLE
What is the best way to transform a null quoted column for Postgres import?

### ISSUE THREAD

**Issue by caboosesw** [C2FO/fast-csv#213]
I have my code working great but it turns out Postgres doesn't like a value to be '' vs. null

I can write my transform after I grab a row of data ... but I was wondering if one of parsing methods is intended to "leave blank" or "don't quote" vs. having me write a method that takes a '' and makes it a Javascript null?

**Comment by doug-martin** [comment]
If you can provide a more in depth example with sample data and the code your using to process it, I can probably help. I suspect you could probably acheive this with transform but Im not sure at this point.

Closing for now but reopen if you can provide an example.
