### ISSUE TITLE
headers option is not functioning correctly

### ISSUE THREAD

**Issue by fudges** [C2FO/fast-csv#218]
I am unable to get the headers option to function correctly in the code below. It keeps treating it as if it's just another line in the file.

```
var fs = require('fs');
var csv = require('fast-csv');
var counter = 0;

let csvStream = csv.fromPath("C:\\x\\test.txt",{delimiter:"\t"}, {headers:true})
  .on("data", function(record){
      csvStream.pause();
      console.log(record);
      csvStream.resume();
  }).on("end", function(){
      console.log("Job is done!!");
  }).on("error", function(){
      console.log(err);
  });
```

**Comment by piuccio** [comment]
I think you want to set

`csv.fromPath("C:\\x\\test.txt", { delimiter:"\t", headers:true })`

Note how the function `fromPath` only takes two arguments, you're passing 3

**Comment by fudges** [comment]
Thank you, @piuccio 
I did not notice that mistake.
