### ISSUE TITLE
Trim not working

### ISSUE THREAD

**Issue by Sammyjroberts** [C2FO/fast-csv#219]
Error: Parse Error: expected: ''' got: 'K'. at ' Kool tee
if i switch quote in config to " i get another error
Parse Error: expected: '"' got: 'm'. at ' music vid

```
let i = 0;
var csvStream = csv.fromStream(stream, {delimiter: "|", quote: "'",  trim: false, escape: "'"})
    .on("data", function(data){
        console.log(i + "/3600000");
        i++
        videos.push(data);
    })
    .on("error", function(err) {
        console.log(err);
    })
    .on("end", function(){
        console.log("done");
    });

stream.pipe(csvStream);
```

**Comment by doug-martin** [comment]
I'd need a sample dataset to see but I suspect its an escaping issue and `fast-csv` cant find the closing quote. 

Closing for now but you can reopen if you can provide a sample dataset and I can then help you debug.
