### ISSUE TITLE
data displayed without semicolon separated by default like inside on the array

### ISSUE THREAD

**Issue by rejais** [C2FO/fast-csv#221]
it's like I have to access the first array first to split it out manually , weird right ? 

I'm just using this command to read the csv File
 `csv.fromPath(fileName, { headers: true })`

the output : 

![screen shot 2018-04-07 at 22 53 23](https://user-images.githubusercontent.com/5574999/38457120-9222a764-3ab6-11e8-8765-ae66d24c5a4e.png)

I expect : 

> nip | start | end | attype
> 880888| 2018.......

any suggestions ? 
thanks

**Comment by doug-martin** [comment]
Based on what I can see in your example you need to set your `delimiter` to ';'
