### ISSUE TITLE
setImmeditate not defined

### ISSUE THREAD

**Issue by codr1** [C2FO/fast-csv#226]
While using fast-csv for the first time in a Chrome extension, got the error that setImmediate is not defined.  

Resolved it by installing the npm package setimmedate.  Then I had to add it in my code as a `require('setimmediate');`
before the require for fast-csv.  And for completeness since I making an extension - I used browserfy.

If anything - I think your documentation should include a few words about this.

**Comment by dustinsmith1024** [comment]
Thanks @codr1.  I don't think any of us have attempted to run fast-csv in the browser. I believe `setImmedate` is just a NodeJs function at this point.

This is good info in case anyone else runs into it though.

If your doing browser based CSV parsing you may want to look into using https://www.papaparse.com/ though.
