### ISSUE TITLE
Doesn't finish reading till the end of file

### ISSUE THREAD

**Issue by naderskhan** [C2FO/fast-csv#230]
I am trying to read a csv with 3million+ rows. With following code, it stops reading at row 3217 and no error thrown.

`
    const fs = require('fs');
    const csv = require('fast-csv');
    const stream = fs.createReadStream(myFile);
    csv
        .fromStream(stream)
        .on('data', function (data) {
            console.log(data);
        })
        .on('end', () => {
            console.log("Done!");
        });
`

**Comment by cggaurav** [comment]
Is there a verbose version that you have tried to see the module logs?

Would this by any chance be related to https://github.com/C2FO/fast-csv/issues/225 ?

**Comment by doug-martin** [comment]
I dont see an error handler on the stream, I'd suspect there is an error being thrown.

Closing for now, reopen if you add the error handler and it does not provide enough info to solve the problem.
