### ISSUE TITLE
row of numbers is in quotes

### ISSUE THREAD

**Issue by Xaviti** [C2FO/fast-csv#231]
Hi, I have a row of numbers which is quoted but I'm not sure why.

Name, "1, 2, 2, 2"

I pass in the numbers as array. Console log right before shows no numbers. 

Is there any way to filter out the quotes? As I don't see them before I cant filter the array.

**Comment by doug-martin** [comment]
Im going to close this. Without a working example that demonstrates the problem I wont be able to accurately reproduce the issue.

If this is still a problem create a new issue with a working example and dataset and Ill help you debug.
