### ISSUE TITLE
[How to] write out the contents of an object?

### ISSUE THREAD

**Issue by mesqueeb** [C2FO/fast-csv#233]
I have this to create a csv:
```js
function handle (data) {
  csv.writeToStream(
    fs.createWriteStream(`${fileName}.csv`),
    [fields].concat(data),
    {headers: true, objectMode: false}
  )
}
```
Even though I put `objectMode` to false, for all fields that have an object as the result it just prints `[object Object]` in that csv cell...
How can I see the actual contents of the object?

Cheers!

**Comment by doug-martin** [comment]
I'm doing some house cleaning for older issues right now so Im going to close this.

BUT, if you can provide a more complete example with example data I can help.
