### ISSUE TITLE
How to parse one single line?

### ISSUE THREAD

**Issue by IonicaBizau** [C2FO/fast-csv#234]
Is there something like this?

```js
csv.parseLineSync('Foo,Bar,Car');
// --> ["Foo", "Bar", "Car"]
```

**Comment by ParkerOu** [comment]
Just use `csv.on("data", (data) => { //your code }`

test.csv
```
foo,bar,ping,pong
John,Cena,Dear,John
```
test.js
```
import csv from 'fast-csv';
import fs from 'fs';


const stream = fs.createReadStream("./test.csv");

csv
 .fromStream(stream, {ignoreEmpty: true})
 .on("data", (data) => {
    console.log(data);
 })
 .on("end", async (data) => {
    console.log('end:', data);
 })
```

output
```
[ 'foo', 'bar', 'ping', 'pong' ]
[ 'John', 'Cena', 'Dear', 'John' ]
end: 2
```

**Comment by IonicaBizau** [comment]
@ParkerOu Sorry, I'm asking how to parse a string from memory, preferably in a sync way.

**Comment by ParkerOu** [comment]
@IonicaBizau I don't get it! This package is for csv.
Do you mean...?
```
const str = 'foo,bar,ping,pong';
const arr = str.split(',');
console.log(arr);
```
output:
```
["foo", "bar", "ping", "pong"]
```

**Comment by IonicaBizau** [comment]
@ParkerOu Exactly! But with all the parsing logic from `fast-csv` (such as providing a delimiter, handling escaping etc).

Your example will fail for `foo,"hello,world",ping,pong`.

**Comment by ParkerOu** [comment]
@IonicaBizau Sorry...I don't understand what you mean?
What's your expect output?

Your input `foo,"hello,world",ping,pong`
Your expect output `[ 'foo', 'hello,world', 'ping', 'pong' ]`???

using this package or just native javascript?

**Comment by IonicaBizau** [comment]
Exactly.

**Comment by doug-martin** [comment]
Im doing some house cleaning, so Im going to close this.

But I think this may be pretty close to what you are looking for.

```js
const parseCsv = csvStr => new Promise((res, rej) => {
    const rows = [];
    csv.parseString(csvStr)
        .on('data', row => rows.push(row))
        .on('error', err => rej(err))
        .on('end', () => res(rows));
});

parseCsv('Foo,Bar,Car').then((rows) => {
    console.log(rows[0]);
});
```

Output:
```
[ 'Foo', 'Bar', 'Car' ]
```
