### ISSUE TITLE
numeric data converted to strings

### ISSUE THREAD

**Issue by shukriadams** [C2FO/fast-csv#235]
When I pass a CSV with numeric content, all numbers are converted to strings, ie, wrapped in double quotes. Is this expected behavior?

**Comment by JynStar725** [comment]
I had same problem (

**Comment by rublev** [comment]
I also have no idea, anyone know how to prevent this? @shukriadams @JynStar725 did either of you figure this out?

**Comment by shukriadams** [comment]
@rublev Nope, never fixed. Treated everything as strings and moved on. Tight schedule and all.

**Comment by rublev** [comment]
@shukriadams FUCK it we'll do it live! FUCK it

**Comment by shukriadams** [comment]
@rublev FWIW I used this to convert terabytes of CSV data on Amazon, so that extra string-based type check per field really hurt.

**Comment by dustinsmith1024** [comment]
Can one of you provide a small example with the options your using?

```js
csv
   .writeToPath("my.csv", [
       {a: "a1", b: 55},
       {a: "a2", b: 2}
   ], {headers: true})
   .on("finish", function(){
      console.log("done!");
   });
```

```sh
▶ c2fo✗ more my.csv
a,b
a1,55
a2,2
```

**Comment by doug-martin** [comment]
I think this may be related to parsing, if that is the case `fast-csv` does not make any assumptions about data types when parsing fields, it gets a buffer and parsed into strings. 

You can transform them using the `transform` method.

If anyone can provide a working example I can help try to clarify.

**Comment by doug-martin** [comment]
Closing for now. Please open a new issue if anyone can provide a working example demonstrating the problem/desired behavior
