### ISSUE TITLE
Does Fast-CSV support with remote csv?

### ISSUE THREAD

**Issue by hengsoheak** [C2FO/fast-csv#236]
I'm working with Typescript project based on NodeJs. I am going to create import feature with to import my some data from `CSV` files to my database. for sure I search more then tow till now can not find any packages suitable for my projects so I would like to asking someone here about `FAST-CSV` feature which support with my current situation or not.

**Comment by dustinsmith1024** [comment]
Fast CSV is used to read in, parse, transform CSV files or data streams. You will need another package to actually write the data into MySQL. There are quite a few options on NPM for interacting with a database. (Sequelize, sqorn, Knex).

If your uploads are large you might need to stream the data from the CSV file into the DB. This is a bit more work but Fast CSV is good at that and will save you from running into any memory issues.

**Comment by hengsoheak** [comment]
Thank you very much now I choose CSVTOJSON packages for doing this process.
