### ISSUE TITLE
[Error] stream async await

### ISSUE THREAD

**Issue by ParkerOu** [C2FO/fast-csv#241]
When I use async in "data", "end" will run first.
Because of the characteristics of JS stream?

My code:
```js
import csv from 'fast-csv';
import fs from 'fs';

const stream = fs.createReadStream("./source/data.csv");

csv
 .fromStream(stream, {ignoreEmpty: true})
 .validate((data) => {
    // some code
 })
 .on("data", async (data) => {
    // some await code
    console.log('1');
    // some await code
    console.log('2');
    // some await code
    console.log('3');
 })
 .on("end", () => {
    console.log('end');
 })
```
Output:
```
end
1
2
3
```

**Comment by MichalCz** [comment]
I stumbled upon this issue...

This is correct behavior. Async functions are executed asynchronously after the event loop ends.

You'd need to use some other means of reading data. Maybe my `scramjet` for instance:

```javascript
DataStream.from(csv
 .fromStream(stream, {ignoreEmpty: true})
 .validate((data) => {
    // some code
 }))
 .consume(async data => console.log('1'))
 .then(() => console.log('end'))
```

Standard node streams won't help much.

**Comment by doug-martin** [comment]
@MichalCz is correct, the `data` event is part of the standard streams library, you could implement a custom stream to pipe into and inside of it you could do your async code.
