### ISSUE TITLE
ignoring headers when column names nominated?

### ISSUE THREAD

**Issue by aspiringguru** [C2FO/fast-csv#243]
The docs advise 

headers=false: Set to true if you expect the first line of your CSV to contain headers, alternatly you can specify an array of headers to use.

I'm using 

  csv.fromStream(stream, {headers : ['colname1', 'colname2', 'colname3']}).on("data", function(data){ ...

which enables addressing each column ie
data['colname1']

but I'm seeing the headers row appear in first row of data retrieved from the .csv

given the wording of the documentation I was expecting the headers row to be ignored when a list of column names is provided.

Am I missing something obvious?

**Comment by rodrigo-visie** [comment]
Any update? I face the same issue.

**Comment by doug-martin** [comment]
You want to specify the `renameHeaders` option to ignore the first row.
