### ISSUE TITLE
TypeError: csv(...).fromStream is not a function

### ISSUE THREAD

**Issue by karajrish** [C2FO/fast-csv#246]
For the below code,
```
var csvfile = "../voter/test.csv";
var fs = require("fs");
var csv = require("fast-csv");
var stream = fs.createReadStream(csvfile);

var csvStream = csv()
  .fromStream(stream, { headers: true })
  .on("data", function(data) {
    console.log(data);
  })
  .on("end", function() {
    console.log(" End of file import");
  });

stream.pipe(csvStream); 
```

I am getting the following error,

```
.fromStream(stream, { headers: true })
   ^

TypeError: csv(...).fromStream is not a function
    at Object.<anonymous> (/***/test.js:26:4)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3
```

I crossed check the library files, the function is present. 
Anything I have missed out? 

> Node version : v8.12.0

**Comment by dustinsmith1024** [comment]
I don't think this library has been used on anything greater than Node 5 and maybe 6. So there are most likely going to be issues in 8.  I'll add 6,7, and 8 to the CI just to see how much breaks.

**Comment by doug-martin** [comment]
This is because your calling `csv().fromStream` instead of `csv.fromStream`. Try removing the parens.

**Comment by Maheswae** [comment]
This is because you might be using upper version of fast-csv package. try to use 2.4.1

**Comment by mayurdanger** [comment]
you can migrate the methods of  version 2.x to 3.x ,
**changes** 
1. fromstream -> parsestream
https://c2fo.io/fast-csv/docs/migration-guides/v2.x-to-v3.x

**Comment by joshverd** [comment]
> you can migrate the methods of version 2.x to 3.x ,
> **changes**
> 
> 1. fromstream -> parsestream
>    https://c2fo.io/fast-csv/docs/migration-guides/v2.x-to-v3.x

parsestream should be parseStream (camel case form), and then it worked fine!

**Comment by jomael-gemota** [comment]
> This is because you might be using upper version of fast-csv package. try to use 2.4.1

Yep, this works for me. Thanks!
