### ISSUE TITLE
insert headers in every row

### ISSUE THREAD

**Issue by miladnouriezade** [C2FO/fast-csv#250]
I'm trying to append an object to csv file, but it adds headers in every row

`  let ws = fs.createWriteStream('./metadata.csv',{flags:'a'});
                csv.write([output],{headers:true}).pipe(ws);`
but as you mentioned in documents, it should add headers once at start of file

**Comment by doug-martin** [comment]
If  you are appending to an existing do you need to set headers to true, as you already have them in the file?

**Comment by doug-martin** [comment]
Ill add some documentation around this see #272
