### ISSUE TITLE
First row of CSV is removed when headers array is provided

### ISSUE THREAD

**Issue by dvddpl** [C2FO/fast-csv#252]
Docs state:
**headers=false**: Set to true if you expect the first line of your CSV to contain headers, alternatively you can specify an array of headers to use.
The first row of my CSV does not contain headers therefore i am passing additional array in the headers parameter.  At first output looked fine. The saved file contains the headers i wanted.  
But then i noticed that the first row ( of valid data! ) of my CSV is beeing removed and replaced by the headers!! 
Docs also state:
renameHeaders=false: **If you want the first line of the file to be removed and replaced by the one provided in the headers option** - Only to be used with headers=[String]
I tried with a CSV file containing headers and i could not see any differences using headers:true or headers:false and when passing headers: [string] the first row is always removed. no matters what renameHeaders is.

**Comment by doug-martin** [comment]
This is fixed in `v3.3.0` #269 I updated the formatting docs and published the new package.
