### ISSUE TITLE
Can support append one line to the last line after call csv.end()?

### ISSUE THREAD

**Issue by luckymore** [C2FO/fast-csv#255]
Once call the `end`, can't append new line to the exist csv file

**Comment by doug-martin** [comment]
Are you wanting to add more data or just a new line to the end of the file? 

If you are just wanting a new line at the end of the file check out `includeEndRowDelimiter` you can find the option in the [formatting docs](https://github.com/C2FO/fast-csv/blob/master/docs/formatting.md)
