### ISSUE TITLE
Can the : be replaced with | for https://github.com/C2FO/fast-csv/issues/201

### ISSUE THREAD

**Issue by rjenningsnypr** [C2FO/fast-csv#265]
In keeping with what MS SQL Studio offers on it's CSV. Colon character is used in too many textual places and it will have to constantly be escaped. The pipe character | would be really useful on CSV output.

Thanks,
Ray Jennings

**Comment by doug-martin** [comment]
I’m not sure I understand. You can change the delimiter when formatting/parsing in `fast-csv`. 

The default is `,` but you can change it to `|`
