### ISSUE TITLE
How to skip first couple of lines?

### ISSUE THREAD

**Issue by digitalblur** [C2FO/fast-csv#27]
We are parsing files from various sources and some of these files we need to potentially skip the first couple of lines. Can you provide some suggestions on how to achieve this? I didnt see any way to do this in the module api.

Thanks!
Tom

**Comment by aryeharmon** [comment]
is it possible for the header to be on the second line?

**Comment by dustinsmith1024** [comment]
I don't think theres anything built in to do it.  I imagine if you do the validate and skip rows your going to lose the header tracking.  I think you could manipulate the file before using fast-csv.  Maybe just strip the line out before hand using standard Node?
