### ISSUE TITLE
[FEATURE] Limit to user defined max number of rows

### ISSUE THREAD

**Issue by cbrittingham** [C2FO/fast-csv#275]
The origin of this feature was a use case where I wanted to read and process headers prior to processing the rest of the data (with the newly defined headers).  

I could see other use cases where you might want to limit the amount of data read. (and perhaps a companion option to start on a given row to support some type of pagination logic)

I have a working solution that adds a maxRows option.

I plan to submit a pull request for consideration.

**Comment by doug-martin** [comment]
release in `v3.6.0`
