### ISSUE TITLE
[FEATURE] Add a warning when parsing the same header twice for one row

### ISSUE THREAD

**Issue by lkappeler** [C2FO/fast-csv#276]
**Lost data and debugged the parser. It turned out I had the same header name twice inside my CSV**
I noticed some difference in the input and output of the parsed file, after some investigation I figured out some fields like description, usually containing html with line breaks where empty. Looked in the parser code, as I expected some errors with the line breaks inside the parsed value. How ever the parser works great  and I found no Issues with parsing the content properly. It turned out that I used the same header multiple times ( from joining some tables to generate the CSV), therefore the first value was overwritten with the second one which is usually empty. 

**Describe the solution you'd like**
A warning would be nice when a already set property on the row gets overwritten. Probably somewhere [here](https://github.com/C2FO/fast-csv/blob/master/src/parser/transforms/HeaderTransformer.ts#L85). Further more a option could be introduced to rename the header if he already exits.

**Comment by doug-martin** [comment]
I changed `fast-csv` to emit an error when duplicate headers are encountered. If you would like to transform them to prevent duplicates `headers` now accepts a function to transform them.
