### ISSUE TITLE
[BUG] Missing export in the Stream Module

### ISSUE THREAD

**Issue by Salemoche** [C2FO/fast-csv#279]
While trying to compile the typescript code running ```tsc -p .```(or npm install for what it's worth) it exits with the following error: 

```node_modules/fast-csv/build/src/formatter/CsvFormatterStream.d.ts:2:21 - error TS2305: Module '"stream"' has no exported member 'TransformCallback'.```
```2 import { Transform, TransformCallback } from 'stream' ```

Anything I can do about it?

**Comment by doug-martin** [comment]
What version of node are you using?

**Comment by Salemoche** [comment]
I'm using 10.16.1

**Comment by polecats** [comment]
Had the same problem when trying to deploy my project to Firebase (firebase deploy)
I've fixed the issue by adding @types/node to my project's dev dependencies.

`npm install @types/node --save-dev`

Got the solution from here 

> https://github.com/rubensworks/sparqljson-parse.js/issues/11#issuecomment-518713100

Hope this helps.

**Comment by doug-martin** [comment]
I've tried a couple of different options to get this to break, but `fast-csv` has `@types/node` is included as a dependency.

If you can provide a short gist or github repo that demonstrates the problem I can try to help fix the issue.

**Comment by SpencerGreene** [comment]
I encountered this same issue.  On investigation, I discovered that my node version was 10.16.x but my @types/node version was 8.10.59.  Once I forced my @types/node to a 10.x verison (actually to 10.17 since there is no 10.16), that cleared it up.
