### ISSUE TITLE
[BUG] Entire lodash is imported, bloating dependencies

### ISSUE THREAD

**Issue by DeneshPohar** [C2FO/fast-csv#281]
Specific functions from `lodash` are being used, but because the entire library is being `import`-ed, bundlers like `webpack` are including all of lodash.

**To Reproduce**
1. Pull fast-csv into a project that's built with `webpack`
2. Look at `webpack` dependencies

**Expected behavior**
Only portions of `lodash` should be imported

E.g., `import isString from 'lodash/isString';`

**Screenshots**
E.g., `import { isString } from 'lodash'; // Bundlers will bring all of lodash here`

**Desktop (please complete the following information):**
n/a

**Additional context**
https://github.com/lodash/lodash/issues/3192

**Comment by doug-martin** [comment]
Fixed in `v3.5.0`
