### ISSUE TITLE
Headers missing while formating an array of objects

### ISSUE THREAD

**Issue by Moltenhead** [C2FO/fast-csv#282]
Hello.

So I pass an array of objects within writeToPath method. Keys are formated this way :
<img width="320" alt="Capture d’écran 2019-09-18 à 13 42 52" src="https://user-images.githubusercontent.com/32105250/65145651-587b6f00-da1a-11e9-93e5-3f87ecbf773c.png">

And some others this way : 
<img width="438" alt="Capture d’écran 2019-09-18 à 13 44 49" src="https://user-images.githubusercontent.com/32105250/65145744-86f94a00-da1a-11e9-8386-f13af2a70fe4.png">

I use this line at the end of my script : 
`csv.writeToPath(outputFile, rows, { headers: true });`

`csv`, containing fast-csv

The trouble I have : 
every keys are produced within the csv export except those from the first screen print that has above 0 index - `housing_request.seeked_types.[1]`, `[2]` and above.
I have no Idea why, but I have to do something like this : 
```js
const headers = []
// [...]
!headers.includes(key) && headers.push(key)
// [...]
csv.writeToPath(outputFile, rows, { headers });
```
To make those appear within the export.

Any idea where it could come from ?
(just to assure you : I 10 times checked the rows and they have the missing keys, it doesn't come from my code)

**Comment by doug-martin** [comment]
@Moltenhead from what I understand it seems like all records do not have the same keys? 

This behavior is expected, take a look at https://c2fo.io/fast-csv/docs/formatting.html#valid-row-types it describes the expected behavior.
