### ISSUE TITLE
[BUG]: Returning Object with empty strings when file size is large

### ISSUE THREAD

**Issue by thakursaurabh1998** [C2FO/fast-csv#285]
**Describe the bug**
I am trying to make database inserts while reading a CSV file.
CSV file is pretty large in size (158 MB) with 2.1 M lines.
`fast-csv` returns normal objects with correct data filled most of the times
```js
{
    userId: "XBHF",
    userName: "John Doe"
}
```
 but randomly starts giving objects with actual keys but the value is empty.

```js
{
    userId: "",
    userName: ""
}
```
This happens approx 300 times while reading the 2.1 M lines, the percentage of error is pretty less but it is there.

**Desktop (please complete the following information):**
 - OS: MacOS (Catalina), Ubuntu 18.04
 - Node Version: v8.15.0

**Comment by doug-martin** [comment]
What version of fast-csv are you using?

**Comment by thakursaurabh1998** [comment]
1.2.0

**Comment by doug-martin** [comment]
@thakursaurabh1998 you should try upgrading to the latest, there were a lot of bugs fixed with the last major release.
