### ISSUE TITLE
NodeJs Heap

### ISSUE THREAD

**Issue by scriptsure** [C2FO/fast-csv#288]
**Describe the bug**
Reading in 400,000 csv files into a database. They are all different sizes but they max out at about 1gig. I was using this method to parse the files. The validate process simply sets some values and creates a table that matches the type of file being processed. I tried to use a stream approach but it is really slow. To load a sample 100 files locally using below approach takes about 4 seconds. If i use the readable way it takes around 80 seconds. When used in production against the 400k files this method blows up due to the file being read in entirely...  Something I am missing here?
```js
const stream = await fast.parseFile(location, {delimiter: '|'})
                .validate(function (data, next) {
                  
                    if (data[0].substring(1) == 'DT' || data[0].substring(1) == 'DA' || data[0].substring(1) == 'RT') {
                        next(null, true);
                    } else if (data[0].substring(1) == 'HD') {
                        if (result && result.tableName) {
                            tableName = result.tableName;
                            next(null, false);
                        } else {
                            //Create the table and save the header record to appropriate table
                            module.exports[data[0]](location, tableName, data, senderId, processSet).then(function (newTable) {
                                tableName = newTable;
                                next(null, false);
                            }).catch(function (err) {
                                next(err, false);
                            });
                        }
                    } else if (data[0] == 'HDR') {
                        senderId = data[2];
                        next(null, false);
                    } else if (data[0].substring(1) == 'TR') {
                        stream.emit('end');
                    } else {
                        next(null, true);
                    }

                })
                .on('data', async (data) => {
                    rowCount += 1;
                    if (rowCount >= global.rowCount) {
                        try {
                            await con.query({
                                sql: `${tableName.sql};`,
                                timeout: 120000,
                                values: [records]
                            });

                            rowCount = 0;
                            records = [];
                        } catch (err) {
                            logger.error(err);
                        }
                    } else {
                        if (data.length === tableName.total) {
                            records.push(data);
                        } else {
                            records.push(extend(data, tableName.total - data.length));
                        }
                    }
                })
                .on("end", async () => {
                    if (rowCount > 0) {
                        try {
                            await con.query({
                                sql: `${tableName.sql};`,
                                timeout: 120000,
                                values: [records]
                            });

                            rowCount = 0;
                            records = [];
                        } catch (err) {
                            logger.error(err);
                        }
                    }

                    tick.stop();
                    var results = t.timers[location];
                    logger.verbose(location + ': ' + results.parse(
                        results.duration()
                    ));
                 
                });

**Comment by scriptsure** [comment]
@doug-martin thanks for the reply... yeah i do need to ensure that the `module.exports[data[0]](location,......` be done before records are read... it creates a new table for each file. SO i need to ensure that the table exists before i perform insert. But i did take the await off the actual insert... running it now. It does take a bit for it to crash

**Comment by scriptsure** [comment]
![image](https://user-images.githubusercontent.com/798281/67798565-21a56980-fa5a-11e9-9cee-0f0b20237fa0.png)

![image](https://user-images.githubusercontent.com/798281/67798870-b8722600-fa5a-11e9-844c-3bd395b3190b.png)

![image](https://user-images.githubusercontent.com/798281/67798894-c162f780-fa5a-11e9-97df-4acb3328ec3b.png)

lookd like GC is working better... memory gets really high though... cpu is killer

**Comment by scriptsure** [comment]
![image](https://user-images.githubusercontent.com/798281/67801328-52d46880-fa5f-11e9-8927-d702662286cf.png)

**Comment by scriptsure** [comment]
wiped out getting this now

![image](https://user-images.githubusercontent.com/798281/67801659-02113f80-fa60-11e9-81fc-95b5ecbf1226.png)

**Comment by doug-martin** [comment]
@scriptsure the problem wasn't with the `await` but that you were using an `await` in an `on('data', => {})` event. 

If you rely anyschronous actions in the `'data'` event  you are guaranteed to run into memory issues. `fast-csv` doesn't know to stop reading when your inserting data, so it keeps reading from the file. If you (implement a transform stream)[`https://nodejs.org/api/stream.html#stream_implementing_a_transform_stream] `fast-csv` will rely on the node `stream` implementation to read data when it is needed.

**Comment by scriptsure** [comment]
@doug-martin gotcha... I took AWAIT out of the data event and much better.

Unfortunately, pretty complicated load... I have to read the first few lines to get specific details from them, then send a call to CREATE the table. So it does have to be done in row order, and I have to wait for the table to finish its creation before the data process can send an INSERT. As I look at it, I will still need the validate to ensure that the initial records do not make it to the data event. Those header records i chuck in the garbage... 

Does it make sense to use the VALIDATE to grab the specifics, then have that lead into the transform where the table is created? Or is it ok to leave as i have it now and have the stream pause while i create the table? Once complete then i kick the read back up with a resume.... I did notice out of the 100,000's or files processed last night for some reason the process never got the table fully created in the validate. So future calls for that file failed.... but it was VERY rare...


                .validate(function (data, next) {

                    if (data[0].substring(1) == 'DT' || data[0].substring(1) == 'DA' || data[0].substring(1) == 'RT') {
                        next(null, true);
                    } else if (data[0].substring(1) == 'HD') {
                        if (result && result.tableName) {
                            tableName = result.tableName;
                            next(null, false);
                        } else {
                            stream.pause();
                            //Create the table and save the header record to appropriate table
                            module.exports[data[0]](location, tableName, data, senderId, processSet).then(function (newTable) {
                                tableName = newTable;
                                stream.resume();
                                next(null, false);
                            }).catch(function (err) {
                                stream.resume();
                                next(err, false);
                            });
                        }
                    } else if (data[0] == 'HDR') {
                        senderId = data[2];
                        next(null, false);
                    } else if (data[0].substring(1) == 'TR') {
                        stream.emit('end');
                    } else {
                        next(null, true);
                    }

**Comment by doug-martin** [comment]
@scriptsure Im sure you figured it out, but yes I would create a function that wraps the stream in a promise so you can throttle how many files you read at a time in another function.

TBH the node streams API can be tough to work with at times, add that to streaming rows into your database and it can be difficult to find where your bottlenecks are.
