### ISSUE TITLE
How to write csv as UTF-16

### ISSUE THREAD

**Issue by energizer92** [C2FO/fast-csv#291]
Hi,

i am not sure if this is even related to this module or might be an issue from another one but...
I created a Excel Workbook with [ExcelJs](https://github.com/exceljs/exceljs) which uses **fast-csv** to write a CSV with the writeBuffer method, afterwards i using [Filesaver](https://github.com/eligrey/FileSaver.js/) to provide a Download.

Is there any Option like {type: 'text/csv;charset=utf-16'} to get the downloaded file not in UTF-8 but in UTF-16.

my Code looks somewhat like this :

````
async function provideCsvDownload(workbook, title){
	// console.log("Building CSV...");
	const buf = await
	workbook.csv.writeBuffer({ delimiter: ';' });

	// console.log("Provide CSV Download...");
	// TODO this type : .. does not help ...
	saveAs(new Blob([ buf ],{type: 'text/csv;charset=utf-16'}), title + '.csv');
}

thanks in advance

**Comment by doug-martin** [comment]
Hi @energizer92 I think you should take a look at an encoding lib. I've never tried the following library but it may suit your needs https://github.com/ashtuchkin/iconv-lite
