### ISSUE TITLE
[BUG] Default import is broken in v3.5.0

### ISSUE THREAD

**Issue by tsimbalar** [C2FO/fast-csv#299]
**Describe the bug**
As of v3.5.0, When importing as 

```ts
import csv from 'fast-csv';
```

and using as 

```ts
csv.writeToStream(stream, rowsWithHeaders, {
      headers: true,
    });
```

I get an error at runtime 

```
TypeError: Cannot read property 'writeToStream' of undefined
```

To fix it, I could import like this : 

```ts
import * as csv from 'fast-csv';
```

and everyting works again

**To Reproduce**
1. `npm install fast-csv@3.5.0`
2. Here is a failing test (with `jest`) : 

```ts
import csv from 'fast-csv';

describe('CSV issue', () => {
  test('should not throw', () => {
    expect(csv).not.toBeUndefined();
  });
});
```

it fails with : 

```
 FAIL  src/api-admin/application/__tests__/repro.spec.ts
  ● CSV issue › should not throw

    expect(received).not.toBeUndefined()

    Received: undefined

      3 | describe('CSV issue', () => {
      4 |   test('should not throw', () => {
    > 5 |     expect(csv).not.toBeUndefined();
        |                     ^
      6 |   });
      7 | });
      8 | 

      at Object.<anonymous> (src/api-admin/application/__tests__/repro.spec.ts:5:21)
```

**Expected behavior**
`import csv from 'fast-csv';` should still work, or this should be a major version bump as it is possibly breaking callers.

**Desktop (please complete the following information):**
 - OS: macOS
 - OS Version Mojave 10.14.6
 - Node Version 12.13.1

**Additional context**
I believe the breakage is due to the changes in `index.ts` in : 

https://github.com/C2FO/fast-csv/commit/28472e54e28888892314493aa5913b4b49f0ed52#diff-f41e9d04a45c83f3b6f6e630f10117fe

**Comment by doug-martin** [comment]
Thanks for reporting, I agree, Ill push out `v3.5.1` and `v3.6.1` with the previous behavior

**Comment by doug-martin** [comment]
@tsimbalar what is your tsconfig? I just tried this with `v3.4.0` and it requires me to use 

`import * as csv from 'fast-csv'`

In https://github.com/C2FO/fast-csv/commit/614b55e8f55959f73e6a98a38b45891a8cff60e7#diff-040c685d1118d71dec69a9e8d10b6e5a which is pre `v3.5.0` I had to import it using the `*` import.

**Comment by tsimbalar** [comment]
Thanks for a quick response Doug 👍 

Our `tsconfig.json` looks like this : 

```json
{
  "compilerOptions": {
    // Basic Options
    "target": "es6",
    "lib": ["es2017", "dom"],
    "rootDir": "src",
    "outDir": "dist",
    "module": "commonjs",
    "moduleResolution": "node",
    "sourceMap": true,
    "inlineSources": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "declaration": true,

    // Strict Type-Checking Options
    "strict": true,

    // Additional Checks
    "noUnusedLocals": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,

    // Experimental Options
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  },
  "include": [
    "src/**/*.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

and we are using `typescript` 3.7.3.

I'm wondering if it may have to do with `"esModuleInterop": true`. 


The generated `.js` when I use  `import csv from 'fast-csv';` looks like : 


```js
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const fast_csv_1 = __importDefault(require("fast-csv"));

// snip ...
```

and places where it ends up using the module looks like : 

```js
fast_csv_1.default.writeToStream(stream, rowsWithHeaders, {
  headers: true,
});
```


When I use `import * as csv from 'fast-csv'` , the generated `js` looks like : 

```js
"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (Object.hasOwnProperty.call(mod, k)) result[k] = mod[k];
    result["default"] = mod;
    return result;
};
Object.defineProperty(exports, "__esModule", { value: true });
const csv = __importStar(require("fast-csv"));

// snip ...
```

and usage looks like : 

```js
csv.writeToStream(stream, rowsWithHeaders, {
  headers: true,
});
```



If I set `"esModuleInterop": false,` in `tsconfig.json` , then indeed it forces me to use `import * as XXX from XXX` , but this actually forces me to change many lib imports all over the codebase. (it's probably something we should do though ...).


So in the end this may be configuration-related. For us it's ok to replace the usage of the import for `fast-csv` and use a `import * as csv`, so publishing a fix might not be 100% necessary , but it's probably worth documenting somewhere that it is a known issue :) 

Thanks !

**Comment by doug-martin** [comment]
I think documentation is a great place to start!

Ill add a some documentation about that. A longer term change would be to provide ts examples along side the js examples. 

Thanks again for pointing this out!

**Comment by doug-martin** [comment]
I've create #301 to address this.
