### ISSUE TITLE
Pause does not work

### ISSUE THREAD

**Issue by formula1** [C2FO/fast-csv#30]
Why is this important?
MongoDB is in many cases the standard to node when it comes to Databases. However if events are emitted faster than Mongoose can handle them, It can result in duplication and or index errors and possibly more

Attempts at solutions and work arounds
1) Pausing the Stream Directly inside of the "record" event

```
stream = fs.createReadStream(filepath);
csvstream = csv.fromStream(stream).on("record", function(data){
stream.pause();
console.log("shouldn't see this more than once");
})
```

stream.pause() doesn't seem to do anything
2) Going into old mode, then pausing directly

```
stream = fs.createReadStream(filepath);
stream.pause();
csvstream = csv.fromStream(stream).on("record", function(data){
stream.pause();
console.log("shouldn't see this more than once");
})
stream.resume();
```

stream.pause() doesn't seem to do anything
3) using pause method of the Parser_Stream
https://github.com/C2FO/fast-csv/blob/master/lib/parser_stream.js#L156

```
stream = fs.createReadStream(filepath);
csvstream = csv.fromStream(stream).on("record", function(data){
csvstream.pause();
console.log("shouldn't see this more than once");
})
```

csvstream.pause() doesn't seem to do anything
4) combining both
https://github.com/C2FO/fast-csv/blob/master/lib/parser_stream.js#L156

```
stream = fs.createReadStream(filepath);
stream.pause();
csvstream = csv.fromStream(stream).on("record", function(data){
stream.pause();
csvstream.pause();
console.log("shouldn't see this more than once");
})
stream.resume();
```

callback doesn't seem to do anything
5) Using csvstream to resume

```
stream = fs.createReadStream(filepath);
stream.pause();
csvstream = csv.fromStream(stream).on("record", function(data){
stream.pause();
csvstream.pause();
console.log("shouldn't see this more than once");
})
csvstream.resume();
```

Process Doesn't start
https://github.com/C2FO/fast-csv/blob/master/lib/parser_stream.js#L163
6) Attempt to see if csvstream.pause() even matters (which it doesn't)

```
stream = fs.createReadStream(filepath);
stream.pause();
csvstream = csv.fromStream(stream).on("record", function(data){
stream.pause();
console.log("shouldn't see this");
})
csvstream.pause();
stream.resume();
```

Doesn't work
7) Using from path

```
csvstream = csv.fromPath(filepath).on("record", function(data){
csvstream.pause();
console.log("shouldn't see this more than once");
})
```

Doesn't work
8) Checking if from path at least prevents it

```
csvstream = csv.fromPath(filepath).on("record", function(data){
console.log("shouldn't see this");
})
csvstream.pause();
```

Doesn't work

**Comment by Xeoncross** [comment]
Can you point me in the right direction? I'm having some bugs with pausing in `2.4.1` where `end` is called while my callbacks are still working on processing from the `data` callbacks.

**Comment by cmmash** [comment]
I'm having the same issue as @Xeoncross .

My `end` callback gets fired before my last row has stopped processing.

**Comment by maximelafarie** [comment]
> Can you point me in the right direction? I'm having some bugs with pausing in `2.4.1` where `end` is called while my callbacks are still working on processing from the `data` callbacks.

Issue still present. I'm also facing it.

**Comment by formula1** [comment]
@maximelafarie One option is to create a [passthrough stream](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) and just push all the records to it. From there you can pause and resume the passthrough stream. That way fast csv can move as quickly as it wants and you can consume each as slowly as you need.

You should probably put the passthrough in [object mode](https://nodejs.org/api/stream.html#object-mode) and push `null` when fast csv ends
