### ISSUE TITLE
[BUG] cannot read property 'parseStream' of undefined

### ISSUE THREAD

**Issue by jjrdev** [C2FO/fast-csv#316]
v.3.5.0 introduced a breaking change ..
import csv from 'fast-csv';
...
       const parser = csv
        .parseStream(stream, {
            headers : true,
            encoding: 'utf-8',
        })
cannot read property 'parseStream' of undefined

**Comment by doug-martin** [comment]
Hi @jjrdev thanks for the issue, this was previously reported and it had to do with ts configuration see https://github.com/C2FO/fast-csv/issues/299
