### ISSUE TITLE
How to get the size of a csvStream?

### ISSUE THREAD

**Issue by dlcrista** [C2FO/fast-csv#322]
I want to get the size of the csvStream that I'm writing to so I can set a Content-Length header when I serve this file. Is this possible to do?

Here's some pseudo-code to give an idea:

```
var headers = {
    "Content-Disposition" : "attachment; filename=mydump.csv",
    "Content-Type" : "text/csv"
//  "Content-Length" : inf

var csvStream = csv.format({headers: true});

client.execute("SELECT * from my_table"), function(row){
    csvStream.write(row);
});
csvStream.end();
csvStream.pipe(res).on("end",process.exit);
```

**Comment by doug-martin** [comment]
Because fast-csv works on streams there is not a way to tell the size before writing the CSV. 

In your example you are selecting from a table which implies that the size is dynamic based on table contents, you would have to write the CSV locally then read the file size in order to know the size.
