### ISSUE TITLE
[BUG] When using writeToStream, stream events don't appear to be emitted

### ISSUE THREAD

**Issue by strigona-worksight** [C2FO/fast-csv#330]
**Describe the bug**
When using writeToStream, stream events don't appear to be emitted.

**Parsing or Formatting?**

 - [X] Formatting
 - [ ] Parsing 

**To Reproduce**

```
import { writeToStream } from '@fast-csv/format';

const rows = [
    ['a', 'b'],
    ['a1', 'b1'],
    ['a2', 'b2'],
];
writeToStream(process.stdout, rows)
.on('finish', () => {
  console.log('format finish');
})
.on('end', () => {
  console.log('format end');
})
.on('close', () => {
  console.log('format close');
})
.on('error', (e) => {
  console.log('format error' + e);
});

console.log('the end...');
```

Output:

```
the end...
a,b
a1,b1
a2,b2
```

**Expected behavior**
I expect the 'finish' and 'end' events to be emitted.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 19.10
 - Node Version v12.16.1
 - fast-csv: 4.0.2

**Comment by doug-martin** [comment]
I think this has to do with `process.stdout`

When I create a custom write stream everything is emitted as expected.

```js
const csv = require('@fast-csv/format');
const { Writable } = require('stream');

const rows = [
    ['a', 'b'],
    ['a1', 'b1'],
    ['a2', 'b2'],
];
const other = new Writable({
    write(chunk, encoding, callback) {
        process.stdout.write(chunk);
        callback();
    },
});
csv.writeToStream(other, rows)
    .on('finish', () => console.log('\nfinish'))
    .on('error', () => console.log('\nerror'));
```
Output;
```
a,b
a1,b1
a2,b2
finish
```

**Comment by doug-martin** [comment]
https://github.com/nodejs/node/issues/7606

**Comment by strigona-worksight** [comment]
Yep, so it is. I hooked up a different destination stream and it's working for me. Thanks for pointing me in the right direction.
