### ISSUE TITLE
[FEATURE] support output quote

### ISSUE THREAD

**Issue by ParkerOu** [C2FO/fast-csv#331]
**Version**
3.7.0
**Parsing or Formatting?**

 - [x] Formatting
 - [ ] Parsing 

**Is your feature request related to a problem? Please describe.**
I want to output csv with double quote.
ex: `"a1","b1"`

Here's my code:
```js
import * as csv from 'fast-csv';

const stream = csv.format({escape: '\"'});
// const stream = csv.format();
stream.pipe(process.stdout);

stream.write(['a1', 'b1']);
stream.write(['"a2"', '"b2"']);
stream.write(['\"a3\"', '\"b3\"']);
stream.end();
```
I expected output would be like:
```
a1,b1
"a2","b2"
"a3","b3"
```
Actual results:
```
a1,b1
"""a2""","""b2"""
"""a3""","""b3"""
```

**Comment by ShehryarShoukat96** [comment]
set quote false in format options:
`const stream = csv.format({escape: '\"', quote: false});`

**Comment by ParkerOu** [comment]
Thanks a lot!
