### ISSUE TITLE
[BUG] Dynamic columns are not being shown

### ISSUE THREAD

**Issue by fabioaarito** [C2FO/fast-csv#334]
**Describe the bug**
Hi guys!
First of all, thank you for your amazing work. This lib is awesome and we're using it in multiple projects. It's good to have people like you contributing to the open-source community.

So, I'm trying to create a CSV using a stream. I'm getting an array of documents from the database and I'm passing the stream and transforming each row to display only the columns I need in the CSV file.

The problem I have is that I have conditional and dynamic columns. For each row, I can have a set of columns that I don't need in another row. And I don't know exactly what are those columns.

For instance, each row can have a subarray of "payments" and in that case, I want one column per payment attribute (Eg: Payment 1 Date, Payment 1 Amount, Payment 2 Date, Payment 2 Amount, ...).

For some reason, these columns are not being shown in the CSV file. 

**Parsing or Formatting?**

 - [X] Formatting
 - [ ] Parsing 

**To Reproduce**
2. Example code to reproduce the issue.

```
const csvStream = fastCsv
      .format({headers: true})
      .transform(row => {
        const paymentsColumns = {};
        if (row.payments.length > 0) {
          paymentsColumns['Total Payment Amount'] = row.totalPaymentAmount;
          row.payments.forEach((payment: ShutoffPayment, index: number) => {
            paymentsColumns[`Payment #${index} Date`] = payment.date;
            paymentsColumns[`Payment #${index} Amount`] = payment.amount;
          });
        }
        return {
          ID: row._id,
          AccountNumber: row.accountNumber,
          ...paymentsColumns,
        };
      });
```

Only the predefined columns (ID and AcountNumber)   
**Expected behavior**
I am expecting to get all the columns in the CSV file.

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: Catalina
 - Node Version 10.19.0

**Comment by doug-martin** [comment]
Hi @fabioaarito 

`fast-csv` will need to know all headers ahead of time, otherwise it will not be able to write headers until all records are processed so it can write the first row, and write the columns in the correct order.

If your dataset is small you could loop through your rows and find all unique columns before hand and provide them as an array to fast-csv.

If you are streaming from the datasource because its a large dataset you may have to stream it twice once to gather the unique headers and again to write the csv.

**Comment by fabioaarito** [comment]
Hi @doug-martin 

Thank you for your help! I'll close the issue then.
