### ISSUE TITLE
[BUG] "Getting Started" button is broken

### ISSUE THREAD

**Issue by ix4** [C2FO/fast-csv#335]
The "Get Started" button on [fast-csv site](https://c2fo.io/fast-csv/) links to `https://c2fo.io/fast-csv/docs/doc1` which is "not found" when it should be linking to `https://c2fo.io/fast-csv/docs/introduction/getting-started`

**Comment by doug-martin** [comment]
Thanks for calling that out, a new version of gh-pages has been published!
