### ISSUE TITLE
[BUG] CSV with no headers does not fail validation

### ISSUE THREAD

**Issue by lantrix** [C2FO/fast-csv#336]
**Describe the bug**

Hi. Using the example [validate_with_reason.example.ts](https://github.com/C2FO/fast-csv/blob/master/examples/parsing-ts/examples/validate_with_reason.example.ts) and this works fine.

However if I remove the header row in the `CSV_STRING` and set `headers: false` the validate function never matches a value of bob, and all records are valid. Output is:

```
Invalid [rowNumber=1] [row={"firstName":"bob","lastName":"yukon"}] [reason=Name is bob]
Valid [row={"firstName":"sally","lastName":"yukon"}]
Valid [row={"firstName":"timmy","lastName":"yukon"}]
Parsed 3 rows
```

**Parsing or Formatting?**

 - [ ] Formatting
 - [x] Parsing 

**To Reproduce**

1. Start with  [validate_with_reason.example.ts](https://github.com/C2FO/fast-csv/blob/master/examples/parsing-ts/examples/validate_with_reason.example.ts)
2. Change the `CSV_STRING` to have no header row, and headers to false.

```typescript
const CSV_STRING = [
  'bob,yukon',
  'sally,yukon',
  'timmy,yukon',
].join(EOL);
```

```typescript
const stream = parse<UserRow, UserRow>({ headers: false })
```

**Expected behavior**

That a `row.firstName` with a value of `bob` would be _Invalid_.

**Screenshots**

The `CSV_STRING` with the same data but no header row has all rows valid. Output is:

```
Valid [row=["bob","yukon"]]
Valid [row=["sally","yukon"]]
Valid [row=["timmy","yukon"]]
Parsed 3 rows
```

![Screenshot 2020-04-08 22 37 54](https://user-images.githubusercontent.com/117008/78785188-087ded00-79ea-11ea-8793-17c389b16d07.png)

**Desktop (please complete the following information):**

 - OS: MacOS 
 - OS Version: Catalina
 - Node Version: v12.16.1
- Typescript Version: 3.8.3

**Additional context**

None. I thought it was bad validate functions I was writing until I took it back to the basics of the example and made the same change.

CSV stream input with only data rows, and `headers: false`.

I also tried node v13.11.0 and same.

`tsconfig.json` is:

```json
{
  "extends": "tsconfig-seek",
  "include": [
    "src/**/*.ts"
  ],
  "compilerOptions": {
    "module": "commonjs",
    "outDir": "./dist",
    "moduleResolution": "node"
  }
}
```

**Comment by doug-martin** [comment]
The example assumes you have headers. Once `headers=false` is set the rows will be arrays.

Because the row is an array, the firstName property does not exist so the check will always be true.
