### ISSUE TITLE
[BUG] Can't parse column containing quoted text

### ISSUE THREAD

**Issue by Inchworm333** [C2FO/fast-csv#337]
**Describe the bug**
When parsing a column that is only partially quoted (ex: `this "is" a test`) I get an error `Error: Parse Error: expected ' ' OR new line got: 'a'. at ' a test`.

**Parsing or Formatting?**

 - [ ] Formatting
 - [x] Parsing 

**To Reproduce**
1. Example file contents if applicable:
		`tt0033122	movie	"Swing it" magistern	"Swing it" magistern	0	1940	\N	92	Comedy,Music`
		(from [IMDB](https://www.imdb.com/interfaces/ "IMDB Datasets"))
2. Example code to reproduce the issue.
	```	
		const insertBulk = db.transaction((rows) => {
			for (const row of rows) insert.run(row);
		})
		
		fastcsv.parseFile(__dirname + '/' + titlesFile, {headers: true, delimiter: '\t'})
		.on('data', row => { //Inserting Data

			insertRows.push(row);

			if(insertRows.length === maxInsert){
				insertBulk(insertRows);
			}
		})
	```

**Expected behavior**
This should parse the problem column as `"Swing it" magistern` instead of throwing an error for a malformed column because the column is not actually malformed.

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: Windows 10 Education
 - OS Version: 1909 (OS build 18363.778)
 - Node Version: v12.3.1

**Additional context**
If this is actually intended could you at least explain why it is and how one could avoid running into this problem / skip the problematic row?

**Comment by doug-martin** [comment]
@Inchworm333 this is because the default quote is set to `"` 

https://c2fo.io/fast-csv/docs/parsing/options#quote

Looking through the file it doesnt look like their is quoting for their format so you can just set that option to `null`

```ts
csv.parseFile('./title.akas.tsv', {headers: true, delimiter: '\t', quote: null})
  .on('error', (err) => console.log(err.stack))
  .on('data', (row: csv.ParserRow) => console.log(`got data ${JSON.stringify(row)}`))
  .on("end", () => console.log("in end"))
  .on("close", () => console.log("in close"));
```

**Comment by doug-martin** [comment]
For little more info, the defaults follow the rules laid out in https://en.wikipedia.org/wiki/Comma-separated_values#Basic_rules
