### ISSUE TITLE
[FEATURE] Example code for stream.pipeline()

### ISSUE THREAD

**Issue by ajmas** [C2FO/fast-csv#339]
**Parsing or Formatting?**

 - [ ] Formatting
 - [x] Parsing 

**Is your feature request related to a problem? Please describe.**

I have been dealing with an issue where `end()` is called before all the data is processed, so I am looking at using the `stream.pipeline` functionality, in NodeJS 12.

**Describe the solution you'd like**

It could be useful to provide an example of how to use fast-csv with the new `stream.pipeline`. Also including an indication of how to be sure that the stream has finished being processed before finishing, especially when using async/await.

**Describe alternatives you've considered**

**Additional context**

**Comment by doug-martin** [comment]
@ajmas do you have an example of when when is being called before your done processing? Are you doing async operations inside of the data listener, or do you have a custom stream you are piping into?

**Comment by datiecher** [comment]
@doug-martin I'm facing this scenario at the moment. Inside my data listener, I have some async operations to perform that I would prefer to handle as each row in the CSV file comes and then wait until all rows are processed and the code inside the data listener is executed in order to proceed with the rest of the script, otherwise I'll have to make the code more complex to achieve the same result.

I'm writing a script to import ~600k products into a database and for each product, I have to first check if the product is already in the db and if so just update its data with the data coming from the CSV, otherwise create a new product and save it to the database. And for each product I also have to execute some other async operations.

My pseudo-code looks something like:

```javascript
fs.createReadStream('my-file.csv')
    .pipe(csv.parse({ headers: true }))
    .on('data', async row => {
        let product = await findMyProduct(row.ID);

        if (product) {
            await updateProduct(product, row);
        } else {
            await createProduct(row);
        }

        await extraStuffForEachRow();
    })
    .on('end', () => cleanupAndLoggingStuff())
;
```

I understand why the listener for the end event is being fired before all the logic inside my listener has run, but since I'm a frontend dev, Node streams are flying over my head and I'm not even sure that promisifying `stream.pipeline` would help me in this case.

**Comment by doug-martin** [comment]
@datiecher Yeah the node streams API isnt super straight forward. I would create a custom stream and pipe into it for this type of use case. 

Take a look at https://nodejs.org/api/stream.html#stream_implementing_a_transform_stream it goes over the basics on implementing a stream, depending on what you need to do 

Here is a quick example of how you **could** do it.

```js
const { EOL } = require('os');

const csv = require('fast-csv');
const { Transform } = require('stream');


class ProductTransformStream extends Transform {
    _write(row, encoding, callback) {
        this.processRow(row).then((product) => {
            console.log(`DONE PROCESSING ROW ${JSON.stringify(row)}`);
            // push product if you want to use it it later streams.
            this.push(product);
            callback();
        }).catch(e => callback(e));
    }

    async processRow(row) {
        const product = await this.findProduct(row);

        if (product) {
            await this.updateProduct(product, row);
        } else {
            await this.createProduct(row);
        }

        await this.extraStuffForEachRow();
        return product;
    }

    async findProduct(row) {
        console.log(`Finding Product ${row.ID}`);
        return Promise.resolve({
            id: row.ID,
            name: row.name,
            price: row.price,
        });
    }

    async updateProduct(product) {
        console.log(`Updating Product ${product.id}`);
        return Promise.resolve(product);
    }

    async extraStuffForEachRow(row) {
        return Promise.resolve(row);
    }
}

const CSV_CONTENT = [
    'ID,name,price',
    `1,Cool Product,$100.00`,
    `2,Lame Product,$100.00`,
].join(EOL);

csv.parseString(CSV_CONTENT, { headers: true })
    .on('error', (e) => console.error(e.stack))
    .pipe(new ProductTransformStream({ objectMode: true }))
    .on('end', () => console.log('DONE!'))
    .on('error', (e) => console.error(e.stack));

```

If you are dealing with thousands of lines you may want to put some batching logic in there so you arent making each request individually.

**Comment by datiecher** [comment]
Thanks a lot, @doug-martin! That's a more elegant and readable implementation of the solution I arrived at after digging deeper into the stream documentation yesterday.

**Comment by Oliboy50** [comment]
just if someone else is looking for the answer, this is what I came up with using `NodeJS 14.*`:

```js
const csv = require('@fast-csv/parse');
const fs = require('fs');
const util = require('util');
const stream = require('stream');
const pipeline = util.promisify(stream.pipeline);

async function myStuff() {
    try {
        await pipeline(
            fs.createReadStream('input.csv'),
            csv.parse({ headers: true }),
            async function* (stream) {
                for await (const { header1, header2 } of stream) {
                    console.log(`header1 is: ${header1}`);
                    console.log(`header2 is: ${header2}`);
                }
            },
        );

        console.log('Success.');
    } catch (e) {
        console.error('Failed.', e);
    }
}

myStuff();
```


Note: thanks to `NodeJS 16.*` promises APIs, we don't need to "promisify" the Stream API ourselves anymore, we can simply do it like this:
```js
const csv = require('@fast-csv/parse');
const fs = require('fs');
const { pipeline } = require('stream/promises');

// same as above ...
```
