### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by trujaytim** [C2FO/fast-csv#340]
**Describe the bug**
When parsing a csv that uses " (double quote) as the quote char and ' (single quote) as the escape char, if a quoted field ends with two single quotes an error is reported. It is expected that two instances of the escape char in a field would escape-the-escape char and so the field would pass parsing successfully.

**Parsing or Formatting?**

 - [ ] Formatting
 - [x] Parsing 

**To Reproduce**
Code sample:
```
  import stream from "stream";
  import csv from "fast-csv";
  const csvString = `Col 1
"A '"Good'" row''"
`;
  const readable = stream.Readable.from(csvString);

    readable
      .pipe(csv.parse({ headers: true, escape: "'" }))
      .on('error', error => console.error(error))
      .on('data', row => console.log(row))
      .on('end', (rowCount) => console.log(`Parsed ${rowCount} rows`)); 
```

**Expected behavior**
Expect a raw field like this (it's a bit hard to read, but this string terminates with two single quotes then a double quote):
> "A '"Good'" row''"

To parse to value:
> A "Good" row'

However instead we get the error:
> "missing closing: '"' in line: at '"A '"Good'" \n'ow''"\n'''"

(not applicable)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Node Version 12.6

**Additional context**

**Comment by doug-martin** [comment]
@trujaytim thank you for the detailed bug report!

A fix has be published under `v4.1.6`
