### ISSUE TITLE
[BUG] Transforming to a different type in Typescript?

### ISSUE THREAD

**Issue by bastiankoetsier** [C2FO/fast-csv#356]
**Describe the bug**
First of all: Thank you very much for this awesome library! 
I was trying to use it in typescript but I have a small issue where it is not possible(?) to use `transform` to map from the InputType to a different OutputType having same properties but different types (sorry for the bad wording, hopefully the example makes this more clear 😅) 

**Parsing or Formatting?**

 - [ ] Formatting
 - [x] Parsing 

**To Reproduce**
My code: 

```ts

type InputRow = {
  clicks: string;
};

type OutputRow = {
  clicks: number;
};
...
  return new Promise((resolve, reject) => {
    const result: any[] = [];
    fs.createReadStream(path.resolve(__dirname, inputFile))
      .pipe(
        parse<InputRow, OutputRow>({ headers: true })
      )
      .on("error", (error: Error) => console.error(error))
      .on("data", (row: any) => {
        result.push(row);
      })
      .transform((data: InputRow): OutputRow => {
        return {
          clicks: parseInt(data.clicks, 10),
         };
      })
      .on("end", () => resolve(result));
  });
```

I was checking the type-definitions and found
```ts
export declare const parse: <I extends Row, O extends Row>...
```
Is there any reason why `O` needs to extends `Row`?

**Expected behavior**
The given output type should not extend `Row`
**Screenshots**
![screenshot](https://user-images.githubusercontent.com/6351038/82140873-49abbd00-9832-11ea-812f-475aa70a509d.png)

If you have any questions, just let me know!

**Comment by doug-martin** [comment]
I added this in `v4.2.0` let me know if you run into any additional issues. 

Thanks again!

**Comment by bastiankoetsier** [comment]
Works like a charm! Thanks for the very quick response @doug-martin !
