### ISSUE TITLE
WriteToStream - Backpressure Issue?

### ISSUE THREAD

**Issue by piobrien** [C2FO/fast-csv#392]
fast-csv version: 4.3.0

I have a function that is used to write the contents of Array of Objects to a csv file with a specific header order. For small arrays I've not seen a problem but I have one array with over 15,000 objects and the if I execute the below the csv file only ends up with about 4,000 of them.

None of the error handling is emitted so finding the issue is problematic,

Do you think this could be a back-pressure issue, I'm not convinced but the silent failure makes me wonder?

```javascript
const { writeToStream } = require('@fast-csv/format');

function writeCSV(filename, headers, data) {
try{
    console.log('Data Contains number of items: ' + data.length');
    const ws = fs.createWriteStream(filename);
    writeToStream(ws, data, { headers: headers, alwaysWriteHeaders: true })
    .on('error', (err) => {
        console.log('Error' + err);
      });
} catch (error) {
    console.log(error);  
}
```

The console shows there's over 15,000 items as expected from the source but the .csv file contains just under 4,000.

**Comment by doug-martin** [comment]
@piobrien what version of node are you running on? 

I just tried an example locally with 10000 records and it wrote out just fine. 

In my test I did the following

```ts
import * as csv from 'fast-csv';
import { createWriteStream } from 'fs';

const rows: csv.FormatterRow[] = [];
for (let i = 0; i < 100000; i += 1) {
  rows.push([`foo${i}`, `bar${i}`, `this is a description ${i}`, (i % 2) === 0]);
}

function writeCSV(filename: string, headers: string[], data: csv.FormatterRow[]) {
  return new Promise((res, rej) => {
    console.log(`Data Contains number of items: ${data.length}`);
    const ws = createWriteStream(filename);
    csv.writeToStream(ws, data, { headers: headers, alwaysWriteHeaders: true })
      .on('error', (err) => rej(err))
      .on('finish', () => res());
  });
}

writeCSV(__dirname + '/output.csv', ['id', 'first', 'last', 'description', 'done'], rows)
  .then(() => console.log("DONE"))
  .catch(e => console.error(e));

```

It might also help if you have an example of input it is failing on so I can try to debug.

**Comment by piobrien** [comment]
@doug-martin 

I'm using nodejs version 14.2.0 on my laptop and I'm also using a AWS Lambda with nodejs with version 12.x

Using the code you provided does work 90% of the time but for some 10% of the time I am getting a small .csv file. I have dumped the array of objects to a file for consistent testing, it has 13,823 objects and each one has 47 attributes.

The curious thing is that when I get a small file the .then and .catch handlers don't fire and nothing is raised in the debugger either, it silently fails.

**Comment by doug-martin** [comment]
That is odd.

I wonder if there is something that isn't being caught and is swallowed by either lambda or node. 
I'll run some tests with that version of node to try to reproduce locally but this sounds like one that maybe hard to pin point.

**Comment by doug-martin** [comment]
Ok, I just tried it with a bunch of headers and was able to reproduce. Give me some time to debug and create a fix.

Thank you for the bug report!

**Comment by doug-martin** [comment]
@piobrien I ran this 100 times locally both with node 12 and 14 and it worked as expected. What is the timeout on your lambda function? 

It looks like the default is 3 seconds that may be too quick for it to complete consistently.

**Comment by piobrien** [comment]
My Lambda has a timeout of 15 minutes and the workstation that I can reproduce on has no timeout. Will try to step through with breakpoints etc. and see if I can find anything.

**Comment by piobrien** [comment]
Good news, this issue seems to be related to my code not allowing enough time for the stream to fully flush down to disk. I was also using VSCode to view the CSV files when testing on my laptop and it looks like it or another process such as AV caused the file to not fully flush out every now and then.

After altering my code structure the lambda completes successfully, apologies for the run around.
