### ISSUE TITLE
How to escape a single qoute in a row

### ISSUE THREAD

**Issue by piobrien** [C2FO/fast-csv#446]
Using Fast-CSV to write a .csv for importing by a SSIS job but it's having issues with apostrophe/single quote in the row.

For example fast-csv writes the row like this: "The quick' brown fox" which SSIS isn't liking, it expects the line to not have the surrounding quotes: The quick' brown fox

Can this be achieved using a transform on a row?
It seems only the contents of the row can be altered using a transform and not the quoting.

**Comment by piobrien** [comment]
Temporarily I'm stripping the single quotes

``` javascript
const transform = row => ({
      TaskName: row.TaskName.replace("'", ""),
    });

    const ws = createWriteStream('transform.csv');
    fastcsv.writeToStream(ws, tasksList, { headers: headers, alwaysWriteHeaders: true, transform: transform })
      .on('error', (err) => rej(err))
      .on('finish', () => res());

```

**Comment by Liotarne** [comment]
I have the same problem with this case :
`
fs.createReadStream(_importFile as string)
              .pipe(csv.parse())
              .on('error', error => reject(error))
              .on('data', row => {
                resp.push(row);
              })
              .on('end', (rowCount: number) => {
                this.logProvider.info(`Parsed ${rowCount} rows`);
                resolve(resp);
              });
`
Do you have any solution please ?

**Comment by doug-martin** [comment]
@piobrien fixed in `v0.4.5`. Thank you for reporting the issue!

**Comment by mabelleeyanhwa** [comment]
How about double quotes?

```
it(`should surround a column value with double quote and leave column value intact
        if column value has single or double quote`, async () => {
      const rows = [ {
        header1: "This column has \"double quotes\"",
        header2: "There is 'single quote'",
      } ];

      const result = await csvFormatter.writeRowsToString(rows);

      expect(result).toEqual("\"This column has \"double quotes\"\"|\"There is 'single quote'\"\n");
    });
```
<img width="944" alt="Screenshot 2020-12-14 at 4 43 22 PM" src="https://user-images.githubusercontent.com/55967697/102059173-7c02b480-3e2b-11eb-9978-822c326ee407.png">

The column that has double quotes is quoted, but the column with single quotes is not quoted

**Comment by mabelleeyanhwa** [comment]
@doug-martin Could you help to check if this behaviour is correct for double quotes?

**Comment by mabelleeyanhwa** [comment]
Hi, @doug-martin @piobrien could you kindly look into this? Our tests are failing because of this change for single quote that did not change for double quote.

**Comment by doug-martin** [comment]
@mabelleeyanhwa sorry I didn't see this notification until this morning...I'll try to take a look today.

**Comment by mabelleeyanhwa** [comment]
@doug-martin its okay, no worries! Thank you for maintaining this package 🍡
