### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by SukanyaPurushothaman** [C2FO/fast-csv#498]
I've searched through the internet and your docs to find the number of sheets in a CSV file. I want to parse the first sheet only.
Please help me with this.

**Comment by doug-martin** [comment]
@SukanyaPurushothaman what do you mean by sheets?

**Comment by robations** [comment]
@SukanyaPurushothaman CSV files don't have sheets. If you export a CSV from (e.g.) Microsoft Excel you can only export one sheet to a CSV. So one sheet, I guess.
