### ISSUE TITLE
[BUG] Unable to set headers without writing header row

### ISSUE THREAD

**Issue by nikolaip** [C2FO/fast-csv#509]
**Describe the bug**
Unable to set headers and but not write the header row.

**Parsing or Formatting?**

 - [x] Formatting
 - [ ] Parsing 

**To Reproduce**
Taken from the examples:
```
var fastCsv = require("fast-csv")

const csvStream = fastCsv.format({ headers: ['header2', 'header1'], writeHeaders: false });

csvStream.pipe(process.stdout).on('end', () => process.exit());

csvStream.write({ header1: 'value1a', header2: 'value2a' });
csvStream.write({ header1: 'value1a', header2: 'value2a' });
csvStream.write({ header1: 'value1a', header2: 'value2a' });
csvStream.write({ header1: 'value1a', header2: 'value2a' });
csvStream.end();
```

**Expected behavior**
```
value2a,value1a
value2a,value1a
value2a,value1a
value2a,value1a
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: Catalina
 - Node Version: v12.18.2

**Additional context**
Looking at the typescript source for the formatter I see:
`this.shouldWriteHeaders = !!this.headers && (opts.writeHeaders ?? true);`
and while I am not comfortable with typescript this looks correct if you are compiling using TypeScript 3.7 as that is when the nullish coalescing was introduced.

However, when looking at the raw javascript in my node_modules directory, the compiled version reads:
`this.shouldWriteHeaders = !!this.headers;`
which looks as if the nullish coalescing has been dropped.

FWIW, I can monkey patch the above like so:
```
var fastCsv = require("fast-csv")

const csvStream = fastCsv.format({ headers: ['header2', 'header1'], writeHeaders: false });
csvStream.rowFormatter.shouldWriteHeaders = false; // monkey patch

csvStream.pipe(process.stdout).on('end', () => process.exit());

csvStream.write({ header1: 'value1a', header2: 'value2a' });
csvStream.write({ header1: 'value1a', header2: 'value2a' });
csvStream.write({ header1: 'value1a', header2: 'value2a' });
csvStream.write({ header1: 'value1a', header2: 'value2a' });
csvStream.end();
```

**Comment by doug-martin** [comment]
@nikolaip I just tried your example locally, I did change it a little bit to make each row different.

```ts
// test.ts
const {format} = require('fast-csv');

const csvStream = format({ headers: ['header2', 'header1'], writeHeaders: false });

csvStream.pipe(process.stdout).on('end', () => process.exit());

csvStream.write({ header1: 'value1a', header2: 'value1b' });
csvStream.write({ header1: 'value2a', header2: 'value2b' });
csvStream.write({ header1: 'value3a', header2: 'value3b' });
csvStream.write({ header1: 'value4a', header2: 'value4b' });
csvStream.end();

```

I received the following output

```
value1b,value1a
value2b,value2a
value3b,value3a
value4b,value4a
```

What version of fast-csv are you using?

**Comment by nikolaip** [comment]
ugh ... I'm sorry, I'm a major version behind (3.7.0). I thought that I had checked before creating the ticket.

https://runkit.com/embed/652yw5u3z4ox

**Comment by doug-martin** [comment]
@nikolaip no problem. Yep, the `writeHeaders` option was't added until [`v4.0.2`](https://github.com/C2FO/fast-csv/blob/master/CHANGELOG.md#v402)
