### ISSUE TITLE
[BUG] Website with documentation not working

### ISSUE THREAD

**Issue by Durisvk** [C2FO/fast-csv#578]
**Describe the bug**
Website with documentation (https://www.c2fo.io/fast-csv) for this library shows 404 error:

**Parsing or Formatting?**

 - [ ] Formatting
 - [ ] Parsing 
 - [x] None of the above

**To Reproduce**
1. Open your browser
2. Type this URL into address bar: https://www.c2fo.io/fast-csv

**Expected behavior**
See the documentation to fast-csv library

**Screenshots**
![image](https://user-images.githubusercontent.com/8467003/104302365-fa08b880-54c8-11eb-949c-8e222c510d2f.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - OS Version: Mojave
 - Node Version: 10.16.0

**Comment by doug-martin** [comment]
Hi @Durisvk

Thank you for reporting @garrypolley is working on fixing this.

-Doug

**Comment by doug-martin** [comment]
@Durisvk the docs are back up, thank you again for reporting!
