### ISSUE TITLE
The new file is up to 65,535 lines , to how to modify the ceiling ?

### ISSUE THREAD

**Issue by kelvinlee** [C2FO/fast-csv#61]
Like title.

I my data has more then 100000. but only can changed 65535 lines.

**Comment by catalint11main** [comment]
that number looks a lot like the row limit in old microsoft excel, open your file with a text editor , you will probably see all rows.

https://www.google.ro/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=microsoft+excel+65535+row+limit

**Comment by kelvinlee** [comment]
@catalint11main  ty very much.

**Comment by catalint** [comment]
@doug-martin you can close this issue
