### ISSUE TITLE
fromPath not Working

### ISSUE THREAD

**Issue by 1Map** [C2FO/fast-csv#617]
In the past I had:

```
csv.fromPath(myFile).on('data', (data) => {
    numfeats++
    if (numfeats === 1) {
        /* Either Header or First Row */
    }
})

```
Now, I get error like:
`csv.fromPath is not a function`

How can the above example be done, and what exactly changed?

**Comment by doug-martin** [comment]
@1Map the method name has changed to `parseFile` https://www.c2fo.io/fast-csv/docs/parsing/methods#parsefile 

Here is a migration guide to help you upgrade https://www.c2fo.io/fast-csv/docs/migration-guides/v2.x-to-v3.x
