### ISSUE TITLE
Why you need @types/node in dependencies?

### ISSUE THREAD

**Issue by Crusader4Christ** [C2FO/fast-csv#770]
https://github.com/C2FO/fast-csv/blob/c6b833d68d3a55440f0d750c921b1039048bc938/packages/format/package.json#L40

Please guys can you move it to devDependencies? Our legacy code use ts3.6 so it can't work with @types/node above version 12.20.20

**Comment by bemon** [comment]
Any idea why they didn't removed it yet ?

**Comment by Crusader4Christ** [comment]
> Any idea why they didn't removed it yet ?
I made the PR for them, but...
https://github.com/C2FO/fast-csv/pull/774

**Comment by zackerydev** [comment]
Fix for this is merged, it will land in the upcoming 5.0 release
