### ISSUE TITLE
[BUG]parse csv file when row has datetime data,return data miss second

### ISSUE THREAD

**Issue by zhuzw1987** [C2FO/fast-csv#778]
**Describe the bug**
i have a csv file, there is some data like **2022/2/23 23:26:27** , i have use **csv.parse({ headers: true })** to parse it, then i get 2022/2/23 23:26, its not right answer.
i read all the document, but nobody say about it.

**Parsing or Formatting?**

 - [x] Formatting
 - [*] Parsing 

**To Reproduce**
file content example: 
E20220223225541084006237,2022-02-23 22:55:41,2022-02-23 22:55:52,2022-03-03 13:22:40,8.00,8.00,,0,,

some code:
fs.createReadStream(filePath)
                .pipe(csv.parse({ headers: true })).on('data', (row) => {console.log(row)});

**Desktop (please complete the following information):**
 - OS: [e.g. MacOS]: MacOS
 - OS Version [e.g. Mojave]: 11.5.2 Big Sur
 - Node Version [e.g. 10.16.0]: 10.15.3

**Additional context**

**Comment by phoenixflutterby** [comment]
F/D
