### ISSUE TITLE
[FEATURE] Is this project dead?

### ISSUE THREAD

**Issue by AnthonyDugarte** [C2FO/fast-csv#789]
**Parsing or Formatting?**

 - [X] Formatting
 - [X] Parsing 

**Is your feature request related to a problem? Please describe.**
it's an excellent package but, the latest version was released 2+ years ago, is it dead?

**Comment by tonivj5** [comment]
> TO add to this, the docs went down.

I have access to it, it's up

**Comment by SimonSchick** [comment]
<img width="846" alt="image" src="https://github.com/C2FO/fast-csv/assets/3259089/821a1af8-bd22-454e-80cb-40a1735a775c">

This is linked from the main readme, can you clarify?

**Comment by tonivj5** [comment]
Use this link instead: https://c2fo.github.io/fast-csv/
![image](https://github.com/C2FO/fast-csv/assets/7110786/80c3a10f-5566-411b-b7d5-e8e469f2205c)

this link is wrong, yep
![image](https://github.com/C2FO/fast-csv/assets/7110786/08cf0319-6efc-4965-89d0-5f5e95e1b803)

**Comment by leeoniya** [comment]
it looks quite dead, so i'll link something far better (just parsing for now): https://github.com/leeoniya/uDSV

**Comment by zackerydev** [comment]
Hey all! I work at C2FO (the owner of this package) and we've admittedly been poor maintainers of this package the last few years!

However - We'd like to get this project back on track, I'll be doing my best to sort through the open issues in the coming weeks.

Thanks!
