### ISSUE TITLE
Formatting Functions example does not work

### ISSUE THREAD

**Issue by digitalblur** [C2FO/fast-csv#79]
Using fast-csv@0.2.5
The first example for "Formatting Functions" does not work. 

The example:
var csvStream = csv.createWriteStream({headers: true}),
    writableStream = fs.createWriteStream("my.csv");

writableStream.on("finish", function(){
  console.log("DONE!");
});

csvStream.pipe(writableStream);
csvStream.write({a: "a0", b: "b0"});
csvStream.write({a: "a1", b: "b1"});
csvStream.write({a: "a2", b: "b2"});
csvStream.write({a: "a3", b: "b4"});
csvStream.write({a: "a3", b: "b4"});
csvStream.end();

Results in:
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Object #<Readable> has no method 'end'

What am I doing wrong?

Thanks

**Comment by doug-martin** [comment]
Please reopen if this is still an issue
