### ISSUE TITLE
download csv

### ISSUE THREAD

**Issue by bhattkrishna19** [C2FO/fast-csv#82]
We are using fast-csv to create a csv report and we want to download this file once its created.  Any idea how can we download this with fast-csv?

**Comment by ruzz311** [comment]
@bhattkrishna19 - I'm making an assumption that you're using [express.js](http://expressjs.com/).  The best way to do this is using streams in fast-csv and piping the result to the client.  

[Check out the fast-csv streaming download example](http://runnable.com/VMhv6vGa_6pnkIKa/fast-csv-streaming-downloads-for-node-js-and-express) I've written with inline comments explaining the juicy bits.

Abbreviated version of the full example using express.
```JavaScript
router.get('/download', function(req, res, next) {
  res.setHeader('Content-disposition', 'attachment; filename=myFile.csv');
  res.setHeader('content-type', 'text/csv');
  var csvStream = csv.createWriteStream({headers: true, objectMode: true});
  csvStream.pipe(res);
  csvStream.write({'col1':'val1', 'col2':'val2'});
  csvStream.end();
});
```

I hope that helps!

**Comment by ruzz311** [comment]
Sorry @bhattkrishna19, I didn't mean to immediately close your issue.  Let me know if this answers your question.

**Comment by xiaogu-space** [comment]
if I use koa,how can I use it?

**Comment by ruzz311** [comment]
Sorry @xiaogu-space, I've never used koa. A small bit of googling I found http://koajs.com/#stream.  Read up on how to use streams and experiment a little, if there's still an issue, please feel free to reply back.

Looks like you might try something similar to this psuedo-code, but really take some time to understand how to implement streams using koa:
```JavaScript
const PassThrough = require('stream').PassThrough;

app.use(async ctx => {
  ctx.set({
    'Content-disposition': 'attachment; filename=myFile.csv',
    'content-type': 'text/csv'
  })
  const csvStream = csv.createWriteStream({headers: true, objectMode: true});
  ctx.body = csvStream.on('error', ctx.onerror).pipe(PassThrough());
  csvStream.write({'col1':'val1', 'col2':'val2'});
  csvStream.end();
});
```

**Comment by ChrisWiles** [comment]
> @bhattkrishna19 - I'm making an assumption that you're using [express.js](http://expressjs.com/). The best way to do this is using streams in fast-csv and piping the result to the client.
> 
> [Check out the fast-csv streaming download example](http://runnable.com/VMhv6vGa_6pnkIKa/fast-csv-streaming-downloads-for-node-js-and-express) I've written with inline comments explaining the juicy bits.
> 
> Abbreviated version of the full example using express.
> 
> ```js
> router.get('/download', function(req, res, next) {
>   res.setHeader('Content-disposition', 'attachment; filename=myFile.csv');
>   res.setHeader('content-type', 'text/csv');
>   var csvStream = csv.createWriteStream({headers: true, objectMode: true});
>   csvStream.pipe(res);
>   csvStream.write({'col1':'val1', 'col2':'val2'});
>   csvStream.end();
> });
> ```
> 
> I hope that helps!

I am getting csv.createWriteStream is not a function running 4.0.2

**Comment by SantoshCode** [comment]
> @bhattkrishna19 - I'm making an assumption that you're using [express.js](http://expressjs.com/). The best way to do this is using streams in fast-csv and piping the result to the client.
> 
> [Check out the fast-csv streaming download example](http://runnable.com/VMhv6vGa_6pnkIKa/fast-csv-streaming-downloads-for-node-js-and-express) I've written with inline comments explaining the juicy bits.
> 
> Abbreviated version of the full example using express.
> 
> ```js
> router.get('/download', function(req, res, next) {
>   res.setHeader('Content-disposition', 'attachment; filename=myFile.csv');
>   res.setHeader('content-type', 'text/csv');
>   var csvStream = csv.createWriteStream({headers: true, objectMode: true});
>   csvStream.pipe(res);
>   csvStream.write({'col1':'val1', 'col2':'val2'});
>   csvStream.end();
> });
> ```
> 
> I hope that helps!

I am getting csv.createWriteStream is not a function running 4.3.6
