### ISSUE TITLE
[BUG] Getting started doc link is broken

### ISSUE THREAD

**Issue by avivshafir** [C2FO/fast-csv#829]
**Describe the bug**
Getting started, doc link is broken, https://c2fo.io/fast-csv/docs/formatting/getting-started

**Comment by daverickdunn** [comment]
Looks like a redirect bucket ain't working. You can view them here: https://c2fo.github.io/fast-csv/docs/parsing/examples/

**Comment by nickyonge** [comment]
Looks like this has a potential fix, https://github.com/C2FO/fast-csv/pull/828 

CC @doug-martin

**Comment by zackerydev** [comment]
This will be fixed in the upcoming 5.0 release.
