### ISSUE TITLE
How to parse file to particular row or upto particular data is received

### ISSUE THREAD

**Issue by KulwantSingh1992** [C2FO/fast-csv#86]
Just wanted to ask how we can parse half of file

**Comment by KulwantSingh1992** [comment]
Hi,
I was trying to parse the csv file which is quite big file and i wanted to parse the file upto paritcular point where i get the data i wanted and wanted the parsing to stop after that but there is no option of stopping the parsing and if there is option to stop parsing how to do that .
actually there was one logic i developed to stop the parsing to assume the content after the data wanted to take as comment but i was not able to use that option.

**Comment by devTristan** [comment]
http://nodejs.org/api/fs.html#fs_fs_createreadstream_path_options

```javascript
fs.createReadStream('sample.csv', {start: 0, end: 1000}) //read the first 1000 bytes
  .pipe( csv({headers: true}) )
  .on('data', function(row){
    console.log('Got row', row);
  })
```

If you want to read exactly half of a file, you can use [fs.stat](http://nodejs.org/api/fs.html#fs_fs_stat_path_callback) to get the size, then divide it by two.

Note that you may get an invalid row at the end if a row gets cut off in the middle.

**Comment by KulwantSingh1992** [comment]
Thanks for the reply ,
but i wanted to parse like first 20 or may be first 30 rows from csv file .so,  how i can get the byte size for these 20 or 30 rows of file.

**Comment by devTristan** [comment]
You can't get the byte size for a certain number of rows unless you already know what's in the file, and in order to do that you (usually) have to read the file.

Here's an example which will read 20 rows and then stop.

```javascript
var fs = require('fs');
var csv = require('fast-csv');

var fileStream = fs.createReadStream('evil.csv', 'utf8');
var csvStream = csv({headers: true});

fileStream.pipe(csvStream);

var rows = [];
var onData = function(row){
  rows.push(row);
  if (rows.length == 20) {
    csvStream.emit('donereading'); //custom event for convenience
  }
};
csvStream.on('data', onData);
csvStream.on('donereading', function(){
  fileStream.close();
  csvStream.removeListener('data', onData);
  console.log('got 20 rows', rows);
});
```

**Comment by KulwantSingh1992** [comment]
Thanks for Reply.
Problem is solved.
