### ISSUE TITLE
Error: write after end

### ISSUE THREAD

**Issue by devTristan** [C2FO/fast-csv#87]
https://gist.github.com/devTristan/5aa69c2822a0da3f5e51

If the stream fast-csv is piped to doesn't always write immediately, I get a `write after end` error. This happens if it waits 100ms every 100 records, or every 10ms on every other record, or pretty much any other combination.

I've tried this with through and through2. I'm not familiar enough with streams to replicate this issue without using a helper module, so it's possible that this bug is present in both through and through2 instead of fast-csv. However, I'm pretty sure this is a fast-csv thing, because I can't replicate it using other csv readers.

Commenting out [this line](https://github.com/C2FO/fast-csv/blob/master/lib/parser/parser_stream.js#L214) prevents this issue from happening, but it also causes a test to fail (specifically, the github issue test for #68).

Help me, @doug-martin, you're my only hope.

**Comment by seamusabshere** [comment]
here's what I get when I run @devTristan's script:

```
$ node -v
v0.10.31

$ git clone https://gist.github.com/5aa69c2822a0da3f5e51.git issue_87
[...]

$ cd issue_87/

issue_87 $ npm install
npm WARN package.json test@0.0.0 No description
npm WARN package.json test@0.0.0 No repository field.
npm WARN package.json test@0.0.0 No README data
through2@0.6.3 node_modules/through2
├── xtend@4.0.0
└── readable-stream@1.0.33 (string_decoder@0.10.31, isarray@0.0.1, inherits@2.0.1, core-util-is@1.0.1)

fast-csv@0.5.5 node_modules/fast-csv
├── is-extended@0.0.10
├── string-extended@0.0.8 (date-extended@0.0.6, array-extended@0.0.11)
├── object-extended@0.0.7 (array-extended@0.0.11)
└── extended@0.0.6 (extender@0.0.10)

issue_87 $ node test.js
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: write after end
    at writeAfterEnd (/Users/seamus/issue_87/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:144:12)
    at DestroyableTransform.Writable.write (/Users/seamus/issue_87/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:192:5)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at DestroyableTransform.<anonymous> (_stream_readable.js:591:7)
    at DestroyableTransform.emit (events.js:92:17)
    at onwriteDrain (/Users/seamus/issue_87/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:300:12)
    at afterWrite (/Users/seamus/issue_87/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:288:5)
    at onwrite (/Users/seamus/issue_87/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:281:7)
    at WritableState.onwrite (/Users/seamus/issue_87/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:106:5)

$
```

**Comment by seamusabshere** [comment]
@doug-martin please help!

**Comment by seamusabshere** [comment]
FYI https://github.com/faradayio/fast-csv/commit/08b46d42c76b1dbe15423ac81c9fa617432bb45d

**Comment by doug-martin** [comment]
Ill be looking into this in a few

**Comment by doug-martin** [comment]
So after some research this issue was caused by two things
  * parser_stream was emitting end during the flush on the transform stream, changed it to not do that, which as you found broke the other tests so I moved the try catch to the emit function
  * In order to create a failing test I had to set a highwater mark of 16 like the through2 library, which was causing it to not read in tall the data at once. 

I added a test in the issues.test which has a transform implementation with the highwater mark set you can test it out if you still have issues let me know!

-Doug

**Comment by doug-martin** [comment]
Please reopen the issue if you still have issues after trying `v0.5.6`

**Comment by seamusabshere** [comment]
@doug-martin love how @devTristan's test was made into a regression test, bravo

**Comment by devTristan** [comment]
:+1:

Thanks @doug-martin !

**Comment by doug-martin** [comment]
@seamusabshere @devTristan Np thanks for using the library!

**Comment by ifalldev** [comment]
Hello everybody!

I'm stuck in this issue. That is my stream pipeline: 
```
const s3 = new AWS.S3({...})
const csvStream = csv({ headers: true }).
  on.('data', ...);
const stream = s3.getObject(params).createReadStream().pipe(csvStream)
```
And that is the error message: `Error [ERR_STREAM_WRITE_AFTER_END]: write after end`

I would appreciate any help, thanks!
