### ISSUE TITLE
[BUG] Breaking changes in the new version 5?

### ISSUE THREAD

**Issue by matthiasfeist** [C2FO/fast-csv#896]
Hi dear team!

Thanks for this fantastic package! I really love it.

I saw that the version has been bumped to the new major version 5 but I can't seem to find any breaking changes.
A new major version would indicate to me that there's a breaking change somewhere.

Was I just too blind to find this in the docs? Or is maybe fast-csv not following semver?

Thanks!

**Comment by zackerydev** [comment]
Hey @matthiasfeist!

Sorry for the delay missed this notification - we dropped support for non LTS versions of node - that's the only change, I will call that out in the README/Changelog!

**Comment by matthiasfeist** [comment]
Perfect. thanks for the information :)
