### ISSUE TITLE
Semicolon support

### ISSUE THREAD

**Issue by SebaCoelli** [C2FO/fast-csv#90]
It would be a great feature to have semicolon support when reading csv files. In many countries the csv file format is delimited by semicolons and not commas.

**Comment by dustinsmith1024** [comment]
Check out the parsing options - https://github.com/C2FO/fast-csv#parsing

You should be able to pass `delimiter=";"` to use semicolons.

**Comment by SebaCoelli** [comment]
Excelent ,

Thank you
