### ISSUE TITLE
fast-csv error stream issues

### ISSUE THREAD

**Issue by jgornick** [C2FO/fast-csv#93]
I ran into an issue when using fast-csv and listening for the error event. It seems a fast-csv stream doesn't properly manage stream events. The example I have is I will thrown an exception outside of the stream and fast-csv stream error event will trigger instead of having it handled via the process.

Example can be found at https://gist.github.com/jgornick/cd2b8bf0d8ba76b5d747

**Comment by doug-martin** [comment]
Hi Joe,

Found the issue and it should be resolved with `v0.6.0` please let me know if you have any issues.

-Doug

**Comment by jgornick** [comment]
@doug-martin Awesomesauce. Thanks!
