### ISSUE TITLE
csv skips rows when writing

### ISSUE THREAD

**Issue by alexyhkim** [C2FO/fast-csv#95]
This code, which should copy a file, will not work for moderately large files (~50 mb)

```
var csv = require('fast-csv');

csv
.fromStream(fs.createReadStream("./input.csv"), {
    headers: true,
    ignoreEmpty: true
})
.transform(function(row) {
    return row;
})
.on("end", function() {
    console.log("done")
})
.pipe(csv.createWriteStream({
}))
.pipe(fs.createWriteStream("./output.csv", {
    encoding: "utf8"
}));
```

The result is many rows will be missing in the output file. My guess is you're not waiting for the 'drain' event before writing to file.

**Comment by fullbl** [comment]
I suppose a bug in writing too
```
    writer = csv.createWriteStream({headers: true,ignoreEmpty: true}),
    stream = fs.createWriteStream('xxx.csv');
    writer.pipe(stream); 

   ....
        writer.write(data);
   ....

```

ends in a lot of blank rows!

**Comment by doug-martin** [comment]
Ill need reproducible example in order to fix.

**Comment by c0bra** [comment]
@doug-martin This is happening to me as well.  Here's an example test script:

```
const fs = require('fs');
const { format } = require("fast-csv");

const data = require("./test.json");

const writeStream = fs.createWriteStream(`test.csv`);
const stream = format({
  quoteColumns: true,
  headers: true,
  quoteHeaders: true,
});
stream.pipe(writeStream);
// stream.setMaxListeners(9999999);

async function run() {
  for (const d of data) {
    if (!stream.write(d)) {
      await new Promise((resolve) => stream.once("drain", resolve));
    }
  }

  stream.end();
  writeStream.end();
}

run();
```

And here's some randomly test data: https://gist.github.com/c0bra/0cf87597ffd6e006b11124b9ea18dc96

There are 300 entries in the json file. If I manually have code that await's the stream's drain event, then 271 rows will be written. If I do not do that, only 271 rows are written.

**Comment by kadusjc** [comment]
i m having the same.. 34 lines writing 25

**Comment by mrsharples** [comment]
Hi, I spent an embarrassingly long time trying to fix this today and I have found I fix that worked for me.

Basically when you pipe the writeStream into the csvStream create an event listener for when the csvStream ends that closes the writeStream. I presume this prevents any async black magic that happens when they are both triggered so closely in sequence.

This is my code

`private async createCSVFile(): Promise<string> {

        //cream write stream directed at file path
        const writeStream = await this.fs.createWriteStream(filePath);
        //create csv stream and declare headers
        const csvStream = csv.format(
            {
                headers:
                    [
                       //list headers of csv
                    ]
            });

        //create an event listener so the write stream only closes after the csv stream has finished writing and ended
        csvStream.pipe(writeStream).on('end', () => writeStream.close());

        //get data from the model
        const reportData = await this.Model.read();

        //map through data and spread values into array alongside required empty values,
        //only works this way because the values returned pefectly match the above headers
        reportData.map(data => {
            csvStream.write([ ...Object.values(data), " ", " " ])
        })

        //end csv stream which triggers write stream to close
        csvStream.end();

    }`
