### ISSUE TITLE
Request: add callback to each row item, so that it can wait before sending next row

### ISSUE THREAD

**Issue by lugog** [C2FO/fast-csv#99]
From the example:
```
var csvStream = csv()
    .on("data", function(data){
         console.log(data);
    })
    .on("end", function(){
         console.log("done");
    });

stream.pipe(csvStream);
```

It would be nice to have this as an option:
```
.on('data', function(data, callback) {} );
```

This way you could do stuff to each row at a time and then not start processing the next row until that was done. 

Example use:
```
.on( 'data', function(data, callback) {
    getWeatherForDay( data, function( err, temp ) {  
               writeDayAndTemp();
               callback(null); 
    });
});
```

Thanks for this library it is very useful!

**Comment by doug-martin** [comment]
The `on("data"` is part of the [streams api](https://nodejs.org/api/stream.html#stream_event_data) so I wont be changing that particular api interface.
